# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: run.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'run.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import uuid_pb2 as uuid__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trun.proto\x12\x11macro_traffic_sim\x1a\nuuid.proto\"C\n\x12RunPipelineRequest\x12-\n\nsession_id\x18\x01 \x01(\x0b\x32\x19.macro_traffic_sim.UUIDv4\"\xe6\x02\n\x13RunPipelineProgress\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\x12-\n\nsession_id\x18\x03 \x01(\x0b\x32\x19.macro_traffic_sim.UUIDv4\x12\r\n\x05phase\x18\x04 \x01(\t\x12\x16\n\x0eperiod_current\x18\x05 \x01(\r\x12\x14\n\x0cperiod_total\x18\x06 \x01(\r\x12\x18\n\x10\x66\x65\x65\x64\x62\x61\x63k_current\x18\x07 \x01(\r\x12\x16\n\x0e\x66\x65\x65\x64\x62\x61\x63k_total\x18\x08 \x01(\r\x12\x1c\n\x14\x61ssignment_iteration\x18\t \x01(\r\x12!\n\x19\x61ssignment_max_iterations\x18\n \x01(\r\x12\x14\n\x0crelative_gap\x18\x0b \x01(\x01\x12\x14\n\x0cis_completed\x18\x0c \x01(\x08\x12\x11\n\tis_failed\x18\r \x01(\x08\x12\x15\n\rerror_message\x18\x0e \x01(\tB@Z>github.com/LdDl/macro_traffic_sim_grpc/clients/go;macrotrafficb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'run_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/LdDl/macro_traffic_sim_grpc/clients/go;macrotraffic'
  _globals['_RUNPIPELINEREQUEST']._serialized_start=44
  _globals['_RUNPIPELINEREQUEST']._serialized_end=111
  _globals['_RUNPIPELINEPROGRESS']._serialized_start=114
  _globals['_RUNPIPELINEPROGRESS']._serialized_end=472
# @@protoc_insertion_point(module_scope)
