# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import uuid_pb2 as uuid__pb2
from . import session_pb2 as session__pb2
from . import network_pb2 as network__pb2
from . import config_pb2 as config__pb2
from . import run_pb2 as run__pb2
from . import results_pb2 as results__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x11macro_traffic_sim\x1a\nuuid.proto\x1a\rsession.proto\x1a\rnetwork.proto\x1a\x0c\x63onfig.proto\x1a\trun.proto\x1a\rresults.proto2\xfa\x08\n\x0cMacroService\x12[\n\nNewSession\x12$.macro_traffic_sim.NewSessionRequest\x1a%.macro_traffic_sim.NewSessionResponse\"\x00\x12U\n\x0bInfoSession\x12\x1c.macro_traffic_sim.SessionId\x1a&.macro_traffic_sim.InfoSessionResponse\"\x00\x12Y\n\rDeleteSession\x12\x1c.macro_traffic_sim.SessionId\x1a(.macro_traffic_sim.DeleteSessionResponse\"\x00\x12]\n\x0bPushNetwork\x12\x1f.macro_traffic_sim.NetworkChunk\x1a\'.macro_traffic_sim.NetworkChunkResponse\"\x00(\x01\x30\x01\x12U\n\tPushZones\x12\x1c.macro_traffic_sim.ZoneChunk\x1a$.macro_traffic_sim.ZoneChunkResponse\"\x00(\x01\x30\x01\x12`\n\x0cPushOdMatrix\x12 .macro_traffic_sim.OdMatrixChunk\x1a(.macro_traffic_sim.OdMatrixChunkResponse\"\x00(\x01\x30\x01\x12\x61\n\x0eSetModelConfig\x12%.macro_traffic_sim.ModelConfigRequest\x1a&.macro_traffic_sim.ModelConfigResponse\"\x00\x12`\n\x0bRunPipeline\x12%.macro_traffic_sim.RunPipelineRequest\x1a&.macro_traffic_sim.RunPipelineProgress\"\x00\x30\x01\x12`\n\x0eGetLinkVolumes\x12%.macro_traffic_sim.LinkVolumesRequest\x1a#.macro_traffic_sim.LinkVolumesChunk\"\x00\x30\x01\x12W\n\rGetSkimMatrix\x12\x1e.macro_traffic_sim.SkimRequest\x1a\".macro_traffic_sim.SkimMatrixChunk\"\x00\x30\x01\x12W\n\x0bGetOdResult\x12\".macro_traffic_sim.OdResultRequest\x1a .macro_traffic_sim.OdResultChunk\"\x00\x30\x01\x12j\n\x11GetAssignmentInfo\x12(.macro_traffic_sim.AssignmentInfoRequest\x1a).macro_traffic_sim.AssignmentInfoResponse\"\x00\x42@Z>github.com/LdDl/macro_traffic_sim_grpc/clients/go;macrotrafficb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/LdDl/macro_traffic_sim_grpc/clients/go;macrotraffic'
  _globals['_MACROSERVICE']._serialized_start=119
  _globals['_MACROSERVICE']._serialized_end=1265
# @@protoc_insertion_point(module_scope)
