# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import config_pb2 as config__pb2
from . import network_pb2 as network__pb2
from . import results_pb2 as results__pb2
from . import run_pb2 as run__pb2
from . import session_pb2 as session__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MacroServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NewSession = channel.unary_unary(
                '/macro_traffic_sim.MacroService/NewSession',
                request_serializer=session__pb2.NewSessionRequest.SerializeToString,
                response_deserializer=session__pb2.NewSessionResponse.FromString,
                _registered_method=True)
        self.InfoSession = channel.unary_unary(
                '/macro_traffic_sim.MacroService/InfoSession',
                request_serializer=session__pb2.SessionId.SerializeToString,
                response_deserializer=session__pb2.InfoSessionResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/macro_traffic_sim.MacroService/DeleteSession',
                request_serializer=session__pb2.SessionId.SerializeToString,
                response_deserializer=session__pb2.DeleteSessionResponse.FromString,
                _registered_method=True)
        self.PushNetwork = channel.stream_stream(
                '/macro_traffic_sim.MacroService/PushNetwork',
                request_serializer=network__pb2.NetworkChunk.SerializeToString,
                response_deserializer=network__pb2.NetworkChunkResponse.FromString,
                _registered_method=True)
        self.PushZones = channel.stream_stream(
                '/macro_traffic_sim.MacroService/PushZones',
                request_serializer=network__pb2.ZoneChunk.SerializeToString,
                response_deserializer=network__pb2.ZoneChunkResponse.FromString,
                _registered_method=True)
        self.PushOdMatrix = channel.stream_stream(
                '/macro_traffic_sim.MacroService/PushOdMatrix',
                request_serializer=network__pb2.OdMatrixChunk.SerializeToString,
                response_deserializer=network__pb2.OdMatrixChunkResponse.FromString,
                _registered_method=True)
        self.SetModelConfig = channel.unary_unary(
                '/macro_traffic_sim.MacroService/SetModelConfig',
                request_serializer=config__pb2.ModelConfigRequest.SerializeToString,
                response_deserializer=config__pb2.ModelConfigResponse.FromString,
                _registered_method=True)
        self.RunPipeline = channel.unary_stream(
                '/macro_traffic_sim.MacroService/RunPipeline',
                request_serializer=run__pb2.RunPipelineRequest.SerializeToString,
                response_deserializer=run__pb2.RunPipelineProgress.FromString,
                _registered_method=True)
        self.GetLinkVolumes = channel.unary_stream(
                '/macro_traffic_sim.MacroService/GetLinkVolumes',
                request_serializer=results__pb2.LinkVolumesRequest.SerializeToString,
                response_deserializer=results__pb2.LinkVolumesChunk.FromString,
                _registered_method=True)
        self.GetSkimMatrix = channel.unary_stream(
                '/macro_traffic_sim.MacroService/GetSkimMatrix',
                request_serializer=results__pb2.SkimRequest.SerializeToString,
                response_deserializer=results__pb2.SkimMatrixChunk.FromString,
                _registered_method=True)
        self.GetOdResult = channel.unary_stream(
                '/macro_traffic_sim.MacroService/GetOdResult',
                request_serializer=results__pb2.OdResultRequest.SerializeToString,
                response_deserializer=results__pb2.OdResultChunk.FromString,
                _registered_method=True)
        self.GetAssignmentInfo = channel.unary_unary(
                '/macro_traffic_sim.MacroService/GetAssignmentInfo',
                request_serializer=results__pb2.AssignmentInfoRequest.SerializeToString,
                response_deserializer=results__pb2.AssignmentInfoResponse.FromString,
                _registered_method=True)


class MacroServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NewSession(self, request, context):
        """Session management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InfoSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushNetwork(self, request_iterator, context):
        """Network data loading (bidirectional streaming for large networks)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushZones(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushOdMatrix(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetModelConfig(self, request, context):
        """Model configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunPipeline(self, request, context):
        """Pipeline execution (server-streaming for progress)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLinkVolumes(self, request, context):
        """Results retrieval (server-streaming for large data)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSkimMatrix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOdResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssignmentInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MacroServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NewSession': grpc.unary_unary_rpc_method_handler(
                    servicer.NewSession,
                    request_deserializer=session__pb2.NewSessionRequest.FromString,
                    response_serializer=session__pb2.NewSessionResponse.SerializeToString,
            ),
            'InfoSession': grpc.unary_unary_rpc_method_handler(
                    servicer.InfoSession,
                    request_deserializer=session__pb2.SessionId.FromString,
                    response_serializer=session__pb2.InfoSessionResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=session__pb2.SessionId.FromString,
                    response_serializer=session__pb2.DeleteSessionResponse.SerializeToString,
            ),
            'PushNetwork': grpc.stream_stream_rpc_method_handler(
                    servicer.PushNetwork,
                    request_deserializer=network__pb2.NetworkChunk.FromString,
                    response_serializer=network__pb2.NetworkChunkResponse.SerializeToString,
            ),
            'PushZones': grpc.stream_stream_rpc_method_handler(
                    servicer.PushZones,
                    request_deserializer=network__pb2.ZoneChunk.FromString,
                    response_serializer=network__pb2.ZoneChunkResponse.SerializeToString,
            ),
            'PushOdMatrix': grpc.stream_stream_rpc_method_handler(
                    servicer.PushOdMatrix,
                    request_deserializer=network__pb2.OdMatrixChunk.FromString,
                    response_serializer=network__pb2.OdMatrixChunkResponse.SerializeToString,
            ),
            'SetModelConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetModelConfig,
                    request_deserializer=config__pb2.ModelConfigRequest.FromString,
                    response_serializer=config__pb2.ModelConfigResponse.SerializeToString,
            ),
            'RunPipeline': grpc.unary_stream_rpc_method_handler(
                    servicer.RunPipeline,
                    request_deserializer=run__pb2.RunPipelineRequest.FromString,
                    response_serializer=run__pb2.RunPipelineProgress.SerializeToString,
            ),
            'GetLinkVolumes': grpc.unary_stream_rpc_method_handler(
                    servicer.GetLinkVolumes,
                    request_deserializer=results__pb2.LinkVolumesRequest.FromString,
                    response_serializer=results__pb2.LinkVolumesChunk.SerializeToString,
            ),
            'GetSkimMatrix': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSkimMatrix,
                    request_deserializer=results__pb2.SkimRequest.FromString,
                    response_serializer=results__pb2.SkimMatrixChunk.SerializeToString,
            ),
            'GetOdResult': grpc.unary_stream_rpc_method_handler(
                    servicer.GetOdResult,
                    request_deserializer=results__pb2.OdResultRequest.FromString,
                    response_serializer=results__pb2.OdResultChunk.SerializeToString,
            ),
            'GetAssignmentInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssignmentInfo,
                    request_deserializer=results__pb2.AssignmentInfoRequest.FromString,
                    response_serializer=results__pb2.AssignmentInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'macro_traffic_sim.MacroService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('macro_traffic_sim.MacroService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MacroService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NewSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macro_traffic_sim.MacroService/NewSession',
            session__pb2.NewSessionRequest.SerializeToString,
            session__pb2.NewSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InfoSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macro_traffic_sim.MacroService/InfoSession',
            session__pb2.SessionId.SerializeToString,
            session__pb2.InfoSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macro_traffic_sim.MacroService/DeleteSession',
            session__pb2.SessionId.SerializeToString,
            session__pb2.DeleteSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushNetwork(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/macro_traffic_sim.MacroService/PushNetwork',
            network__pb2.NetworkChunk.SerializeToString,
            network__pb2.NetworkChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushZones(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/macro_traffic_sim.MacroService/PushZones',
            network__pb2.ZoneChunk.SerializeToString,
            network__pb2.ZoneChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushOdMatrix(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/macro_traffic_sim.MacroService/PushOdMatrix',
            network__pb2.OdMatrixChunk.SerializeToString,
            network__pb2.OdMatrixChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetModelConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macro_traffic_sim.MacroService/SetModelConfig',
            config__pb2.ModelConfigRequest.SerializeToString,
            config__pb2.ModelConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/macro_traffic_sim.MacroService/RunPipeline',
            run__pb2.RunPipelineRequest.SerializeToString,
            run__pb2.RunPipelineProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLinkVolumes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/macro_traffic_sim.MacroService/GetLinkVolumes',
            results__pb2.LinkVolumesRequest.SerializeToString,
            results__pb2.LinkVolumesChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSkimMatrix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/macro_traffic_sim.MacroService/GetSkimMatrix',
            results__pb2.SkimRequest.SerializeToString,
            results__pb2.SkimMatrixChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOdResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/macro_traffic_sim.MacroService/GetOdResult',
            results__pb2.OdResultRequest.SerializeToString,
            results__pb2.OdResultChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssignmentInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macro_traffic_sim.MacroService/GetAssignmentInfo',
            results__pb2.AssignmentInfoRequest.SerializeToString,
            results__pb2.AssignmentInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
