# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: session.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import uuid_pb2 as uuid__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsession.proto\x12\x11macro_traffic_sim\x1a\nuuid.proto\"\x13\n\x11NewSessionRequest\"_\n\x12NewSessionResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\x12-\n\nsession_id\x18\x03 \x01(\x0b\x32\x19.macro_traffic_sim.UUIDv4\"5\n\tSessionId\x12(\n\x05value\x18\x01 \x01(\x0b\x32\x19.macro_traffic_sim.UUIDv4\"\x90\x02\n\x13InfoSessionResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\x12-\n\nsession_id\x18\x03 \x01(\x0b\x32\x19.macro_traffic_sim.UUIDv4\x12\r\n\x05state\x18\x04 \x01(\t\x12\x13\n\x0bhas_network\x18\x05 \x01(\x08\x12\x11\n\thas_zones\x18\x06 \x01(\x08\x12\x15\n\rhas_od_matrix\x18\x07 \x01(\x08\x12\x12\n\nhas_config\x18\x08 \x01(\x08\x12\x13\n\x0bhas_results\x18\t \x01(\x08\x12\x11\n\tnum_nodes\x18\n \x01(\r\x12\x11\n\tnum_links\x18\x0b \x01(\r\x12\x11\n\tnum_zones\x18\x0c \x01(\r\"3\n\x15\x44\x65leteSessionResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\tB@Z>github.com/LdDl/macro_traffic_sim_grpc/clients/go;macrotrafficb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/LdDl/macro_traffic_sim_grpc/clients/go;macrotraffic'
  _globals['_NEWSESSIONREQUEST']._serialized_start=48
  _globals['_NEWSESSIONREQUEST']._serialized_end=67
  _globals['_NEWSESSIONRESPONSE']._serialized_start=69
  _globals['_NEWSESSIONRESPONSE']._serialized_end=164
  _globals['_SESSIONID']._serialized_start=166
  _globals['_SESSIONID']._serialized_end=219
  _globals['_INFOSESSIONRESPONSE']._serialized_start=222
  _globals['_INFOSESSIONRESPONSE']._serialized_end=494
  _globals['_DELETESESSIONRESPONSE']._serialized_start=496
  _globals['_DELETESESSIONRESPONSE']._serialized_end=547
# @@protoc_insertion_point(module_scope)
