// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: config.proto

package macrotraffic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Assignment algorithm selection
type AssignmentMethod int32

const (
	AssignmentMethod_ASSIGNMENT_FRANK_WOLFE         AssignmentMethod = 0
	AssignmentMethod_ASSIGNMENT_MSA                 AssignmentMethod = 1
	AssignmentMethod_ASSIGNMENT_GRADIENT_PROJECTION AssignmentMethod = 2
)

// Enum value maps for AssignmentMethod.
var (
	AssignmentMethod_name = map[int32]string{
		0: "ASSIGNMENT_FRANK_WOLFE",
		1: "ASSIGNMENT_MSA",
		2: "ASSIGNMENT_GRADIENT_PROJECTION",
	}
	AssignmentMethod_value = map[string]int32{
		"ASSIGNMENT_FRANK_WOLFE":         0,
		"ASSIGNMENT_MSA":                 1,
		"ASSIGNMENT_GRADIENT_PROJECTION": 2,
	}
)

func (x AssignmentMethod) Enum() *AssignmentMethod {
	p := new(AssignmentMethod)
	*p = x
	return p
}

func (x AssignmentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssignmentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[0].Descriptor()
}

func (AssignmentMethod) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[0]
}

func (x AssignmentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssignmentMethod.Descriptor instead.
func (AssignmentMethod) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

// Impedance function type for trip distribution
type ImpedanceFunctionType int32

const (
	ImpedanceFunctionType_IMPEDANCE_EXPONENTIAL ImpedanceFunctionType = 0
	ImpedanceFunctionType_IMPEDANCE_POWER       ImpedanceFunctionType = 1
	ImpedanceFunctionType_IMPEDANCE_COMBINED    ImpedanceFunctionType = 2
)

// Enum value maps for ImpedanceFunctionType.
var (
	ImpedanceFunctionType_name = map[int32]string{
		0: "IMPEDANCE_EXPONENTIAL",
		1: "IMPEDANCE_POWER",
		2: "IMPEDANCE_COMBINED",
	}
	ImpedanceFunctionType_value = map[string]int32{
		"IMPEDANCE_EXPONENTIAL": 0,
		"IMPEDANCE_POWER":       1,
		"IMPEDANCE_COMBINED":    2,
	}
)

func (x ImpedanceFunctionType) Enum() *ImpedanceFunctionType {
	p := new(ImpedanceFunctionType)
	*p = x
	return p
}

func (x ImpedanceFunctionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImpedanceFunctionType) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[1].Descriptor()
}

func (ImpedanceFunctionType) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[1]
}

func (x ImpedanceFunctionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImpedanceFunctionType.Descriptor instead.
func (ImpedanceFunctionType) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

// Trip generation method
type TripGenerationMethod int32

const (
	TripGenerationMethod_TRIP_GEN_REGRESSION           TripGenerationMethod = 0
	TripGenerationMethod_TRIP_GEN_CROSS_CLASSIFICATION TripGenerationMethod = 1
)

// Enum value maps for TripGenerationMethod.
var (
	TripGenerationMethod_name = map[int32]string{
		0: "TRIP_GEN_REGRESSION",
		1: "TRIP_GEN_CROSS_CLASSIFICATION",
	}
	TripGenerationMethod_value = map[string]int32{
		"TRIP_GEN_REGRESSION":           0,
		"TRIP_GEN_CROSS_CLASSIFICATION": 1,
	}
)

func (x TripGenerationMethod) Enum() *TripGenerationMethod {
	p := new(TripGenerationMethod)
	*p = x
	return p
}

func (x TripGenerationMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TripGenerationMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[2].Descriptor()
}

func (TripGenerationMethod) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[2]
}

func (x TripGenerationMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TripGenerationMethod.Descriptor instead.
func (TripGenerationMethod) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

// BPR volume-delay function parameters
// t = t0 * (1 + alpha * (V/C)^beta)
type BprConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scale of delay at capacity. Default 0.15.
	Alpha float64 `protobuf:"fixed64,1,opt,name=alpha,proto3" json:"alpha,omitempty"`
	// Non-linearity exponent. Default 4.0.
	Beta          float64 `protobuf:"fixed64,2,opt,name=beta,proto3" json:"beta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BprConfig) Reset() {
	*x = BprConfig{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BprConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BprConfig) ProtoMessage() {}

func (x *BprConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BprConfig.ProtoReflect.Descriptor instead.
func (*BprConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *BprConfig) GetAlpha() float64 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

func (x *BprConfig) GetBeta() float64 {
	if x != nil {
		return x.Beta
	}
	return 0
}

// Assignment convergence parameters
type AssignmentConvergence struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of iterations. Default 100.
	MaxIterations uint32 `protobuf:"varint,1,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	// Relative gap threshold. Default 0.001.
	ConvergenceGap float64 `protobuf:"fixed64,2,opt,name=convergence_gap,json=convergenceGap,proto3" json:"convergence_gap,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssignmentConvergence) Reset() {
	*x = AssignmentConvergence{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignmentConvergence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentConvergence) ProtoMessage() {}

func (x *AssignmentConvergence) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentConvergence.ProtoReflect.Descriptor instead.
func (*AssignmentConvergence) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *AssignmentConvergence) GetMaxIterations() uint32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *AssignmentConvergence) GetConvergenceGap() float64 {
	if x != nil {
		return x.ConvergenceGap
	}
	return 0
}

// Furness (IPF) balancing parameters
type FurnessConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum iterations. Default 100.
	MaxIterations uint32 `protobuf:"varint,1,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	// Row/column sum tolerance. Default 0.001.
	Tolerance     float64 `protobuf:"fixed64,2,opt,name=tolerance,proto3" json:"tolerance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FurnessConfig) Reset() {
	*x = FurnessConfig{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FurnessConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FurnessConfig) ProtoMessage() {}

func (x *FurnessConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FurnessConfig.ProtoReflect.Descriptor instead.
func (*FurnessConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *FurnessConfig) GetMaxIterations() uint32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *FurnessConfig) GetTolerance() float64 {
	if x != nil {
		return x.Tolerance
	}
	return 0
}

// Impedance (deterrence) function for gravity model
type ImpedanceFunction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Function type
	Type ImpedanceFunctionType `protobuf:"varint,1,opt,name=type,proto3,enum=macro_traffic_sim.ImpedanceFunctionType" json:"type,omitempty"`
	// Power exponent (for POWER and COMBINED). Default 2.0.
	Alpha float64 `protobuf:"fixed64,2,opt,name=alpha,proto3" json:"alpha,omitempty"`
	// Exponential decay (for EXPONENTIAL and COMBINED). Default 0.1.
	Beta          float64 `protobuf:"fixed64,3,opt,name=beta,proto3" json:"beta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpedanceFunction) Reset() {
	*x = ImpedanceFunction{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpedanceFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpedanceFunction) ProtoMessage() {}

func (x *ImpedanceFunction) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpedanceFunction.ProtoReflect.Descriptor instead.
func (*ImpedanceFunction) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *ImpedanceFunction) GetType() ImpedanceFunctionType {
	if x != nil {
		return x.Type
	}
	return ImpedanceFunctionType_IMPEDANCE_EXPONENTIAL
}

func (x *ImpedanceFunction) GetAlpha() float64 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

func (x *ImpedanceFunction) GetBeta() float64 {
	if x != nil {
		return x.Beta
	}
	return 0
}

// Regression coefficients for trip generation
// value = intercept + pop*pop_coeff + emp*emp_coeff + hh*hh_coeff + income*income_coeff
type RegressionCoeffs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intercept     float64                `protobuf:"fixed64,1,opt,name=intercept,proto3" json:"intercept,omitempty"`
	PopCoeff      float64                `protobuf:"fixed64,2,opt,name=pop_coeff,json=popCoeff,proto3" json:"pop_coeff,omitempty"`
	EmpCoeff      float64                `protobuf:"fixed64,3,opt,name=emp_coeff,json=empCoeff,proto3" json:"emp_coeff,omitempty"`
	HhCoeff       float64                `protobuf:"fixed64,4,opt,name=hh_coeff,json=hhCoeff,proto3" json:"hh_coeff,omitempty"`
	IncomeCoeff   float64                `protobuf:"fixed64,5,opt,name=income_coeff,json=incomeCoeff,proto3" json:"income_coeff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegressionCoeffs) Reset() {
	*x = RegressionCoeffs{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegressionCoeffs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegressionCoeffs) ProtoMessage() {}

func (x *RegressionCoeffs) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegressionCoeffs.ProtoReflect.Descriptor instead.
func (*RegressionCoeffs) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *RegressionCoeffs) GetIntercept() float64 {
	if x != nil {
		return x.Intercept
	}
	return 0
}

func (x *RegressionCoeffs) GetPopCoeff() float64 {
	if x != nil {
		return x.PopCoeff
	}
	return 0
}

func (x *RegressionCoeffs) GetEmpCoeff() float64 {
	if x != nil {
		return x.EmpCoeff
	}
	return 0
}

func (x *RegressionCoeffs) GetHhCoeff() float64 {
	if x != nil {
		return x.HhCoeff
	}
	return 0
}

func (x *RegressionCoeffs) GetIncomeCoeff() float64 {
	if x != nil {
		return x.IncomeCoeff
	}
	return 0
}

// Trip generation configuration
type TripGenerationConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generation method
	Method TripGenerationMethod `protobuf:"varint,1,opt,name=method,proto3,enum=macro_traffic_sim.TripGenerationMethod" json:"method,omitempty"`
	// Regression: production coefficients
	ProductionCoeffs *RegressionCoeffs `protobuf:"bytes,2,opt,name=production_coeffs,json=productionCoeffs,proto3" json:"production_coeffs,omitempty"`
	// Regression: attraction coefficients
	AttractionCoeffs *RegressionCoeffs `protobuf:"bytes,3,opt,name=attraction_coeffs,json=attractionCoeffs,proto3" json:"attraction_coeffs,omitempty"`
	// Cross-classification: attraction rate per employee
	AttractionRatePerEmployee float64 `protobuf:"fixed64,4,opt,name=attraction_rate_per_employee,json=attractionRatePerEmployee,proto3" json:"attraction_rate_per_employee,omitempty"`
	// Cross-classification: household size category thresholds
	HhSizeThresholds []float64 `protobuf:"fixed64,5,rep,packed,name=hh_size_thresholds,json=hhSizeThresholds,proto3" json:"hh_size_thresholds,omitempty"`
	// Cross-classification: income category thresholds
	IncomeThresholds []float64 `protobuf:"fixed64,6,rep,packed,name=income_thresholds,json=incomeThresholds,proto3" json:"income_thresholds,omitempty"`
	// Cross-classification: production rates by category key "row_col" -> rate
	ProductionRates map[string]float64 `protobuf:"bytes,7,rep,name=production_rates,json=productionRates,proto3" json:"production_rates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TripGenerationConfig) Reset() {
	*x = TripGenerationConfig{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripGenerationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripGenerationConfig) ProtoMessage() {}

func (x *TripGenerationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripGenerationConfig.ProtoReflect.Descriptor instead.
func (*TripGenerationConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *TripGenerationConfig) GetMethod() TripGenerationMethod {
	if x != nil {
		return x.Method
	}
	return TripGenerationMethod_TRIP_GEN_REGRESSION
}

func (x *TripGenerationConfig) GetProductionCoeffs() *RegressionCoeffs {
	if x != nil {
		return x.ProductionCoeffs
	}
	return nil
}

func (x *TripGenerationConfig) GetAttractionCoeffs() *RegressionCoeffs {
	if x != nil {
		return x.AttractionCoeffs
	}
	return nil
}

func (x *TripGenerationConfig) GetAttractionRatePerEmployee() float64 {
	if x != nil {
		return x.AttractionRatePerEmployee
	}
	return 0
}

func (x *TripGenerationConfig) GetHhSizeThresholds() []float64 {
	if x != nil {
		return x.HhSizeThresholds
	}
	return nil
}

func (x *TripGenerationConfig) GetIncomeThresholds() []float64 {
	if x != nil {
		return x.IncomeThresholds
	}
	return nil
}

func (x *TripGenerationConfig) GetProductionRates() map[string]float64 {
	if x != nil {
		return x.ProductionRates
	}
	return nil
}

// Mode utility coefficients
// V = asc + coeff_time * time + coeff_distance * distance + coeff_cost * cost
type ModeUtility struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mode name: "auto", "bike", "walk"
	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// Alternative-specific constant
	Asc float64 `protobuf:"fixed64,2,opt,name=asc,proto3" json:"asc,omitempty"`
	// Travel time coefficient (typically negative)
	CoeffTime float64 `protobuf:"fixed64,3,opt,name=coeff_time,json=coeffTime,proto3" json:"coeff_time,omitempty"`
	// Travel distance coefficient (typically negative)
	CoeffDistance float64 `protobuf:"fixed64,4,opt,name=coeff_distance,json=coeffDistance,proto3" json:"coeff_distance,omitempty"`
	// Monetary cost coefficient (typically negative)
	CoeffCost     float64 `protobuf:"fixed64,5,opt,name=coeff_cost,json=coeffCost,proto3" json:"coeff_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeUtility) Reset() {
	*x = ModeUtility{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeUtility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeUtility) ProtoMessage() {}

func (x *ModeUtility) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeUtility.ProtoReflect.Descriptor instead.
func (*ModeUtility) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *ModeUtility) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ModeUtility) GetAsc() float64 {
	if x != nil {
		return x.Asc
	}
	return 0
}

func (x *ModeUtility) GetCoeffTime() float64 {
	if x != nil {
		return x.CoeffTime
	}
	return 0
}

func (x *ModeUtility) GetCoeffDistance() float64 {
	if x != nil {
		return x.CoeffDistance
	}
	return 0
}

func (x *ModeUtility) GetCoeffCost() float64 {
	if x != nil {
		return x.CoeffCost
	}
	return 0
}

// Time period for multi-period analysis
type TimePeriod struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Period name (e.g. "AM peak")
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Start hour (e.g. 7.0 = 07:00)
	StartHour float64 `protobuf:"fixed64,2,opt,name=start_hour,json=startHour,proto3" json:"start_hour,omitempty"`
	// End hour (e.g. 10.0 = 10:00)
	EndHour float64 `protobuf:"fixed64,3,opt,name=end_hour,json=endHour,proto3" json:"end_hour,omitempty"`
	// Demand multiplier for this period (1.0 = full OD matrix)
	DemandFactor  float64 `protobuf:"fixed64,4,opt,name=demand_factor,json=demandFactor,proto3" json:"demand_factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimePeriod) Reset() {
	*x = TimePeriod{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimePeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimePeriod) ProtoMessage() {}

func (x *TimePeriod) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimePeriod.ProtoReflect.Descriptor instead.
func (*TimePeriod) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{7}
}

func (x *TimePeriod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TimePeriod) GetStartHour() float64 {
	if x != nil {
		return x.StartHour
	}
	return 0
}

func (x *TimePeriod) GetEndHour() float64 {
	if x != nil {
		return x.EndHour
	}
	return 0
}

func (x *TimePeriod) GetDemandFactor() float64 {
	if x != nil {
		return x.DemandFactor
	}
	return 0
}

// Complete model configuration request
type ModelConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session identifier
	SessionId *UUIDv4 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Assignment algorithm
	AssignmentMethod AssignmentMethod `protobuf:"varint,2,opt,name=assignment_method,json=assignmentMethod,proto3,enum=macro_traffic_sim.AssignmentMethod" json:"assignment_method,omitempty"`
	// BPR parameters
	Bpr *BprConfig `protobuf:"bytes,3,opt,name=bpr,proto3" json:"bpr,omitempty"`
	// Assignment convergence settings
	Assignment *AssignmentConvergence `protobuf:"bytes,4,opt,name=assignment,proto3" json:"assignment,omitempty"`
	// Furness balancing settings
	Furness *FurnessConfig `protobuf:"bytes,5,opt,name=furness,proto3" json:"furness,omitempty"`
	// Number of feedback loop iterations (min 1)
	FeedbackIterations uint32 `protobuf:"varint,6,opt,name=feedback_iterations,json=feedbackIterations,proto3" json:"feedback_iterations,omitempty"`
	// GP step scale (only for GRADIENT_PROJECTION method)
	GpStepScale float64 `protobuf:"fixed64,7,opt,name=gp_step_scale,json=gpStepScale,proto3" json:"gp_step_scale,omitempty"`
	// Impedance function for gravity model
	Impedance *ImpedanceFunction `protobuf:"bytes,8,opt,name=impedance,proto3" json:"impedance,omitempty"`
	// Trip generation parameters
	TripGeneration *TripGenerationConfig `protobuf:"bytes,9,opt,name=trip_generation,json=tripGeneration,proto3" json:"trip_generation,omitempty"`
	// Mode choice utility functions (one per mode)
	ModeUtilities []*ModeUtility `protobuf:"bytes,10,rep,name=mode_utilities,json=modeUtilities,proto3" json:"mode_utilities,omitempty"`
	// Time periods for multi-period analysis (empty = single period)
	TimePeriods   []*TimePeriod `protobuf:"bytes,11,rep,name=time_periods,json=timePeriods,proto3" json:"time_periods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelConfigRequest) Reset() {
	*x = ModelConfigRequest{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelConfigRequest) ProtoMessage() {}

func (x *ModelConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelConfigRequest.ProtoReflect.Descriptor instead.
func (*ModelConfigRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8}
}

func (x *ModelConfigRequest) GetSessionId() *UUIDv4 {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *ModelConfigRequest) GetAssignmentMethod() AssignmentMethod {
	if x != nil {
		return x.AssignmentMethod
	}
	return AssignmentMethod_ASSIGNMENT_FRANK_WOLFE
}

func (x *ModelConfigRequest) GetBpr() *BprConfig {
	if x != nil {
		return x.Bpr
	}
	return nil
}

func (x *ModelConfigRequest) GetAssignment() *AssignmentConvergence {
	if x != nil {
		return x.Assignment
	}
	return nil
}

func (x *ModelConfigRequest) GetFurness() *FurnessConfig {
	if x != nil {
		return x.Furness
	}
	return nil
}

func (x *ModelConfigRequest) GetFeedbackIterations() uint32 {
	if x != nil {
		return x.FeedbackIterations
	}
	return 0
}

func (x *ModelConfigRequest) GetGpStepScale() float64 {
	if x != nil {
		return x.GpStepScale
	}
	return 0
}

func (x *ModelConfigRequest) GetImpedance() *ImpedanceFunction {
	if x != nil {
		return x.Impedance
	}
	return nil
}

func (x *ModelConfigRequest) GetTripGeneration() *TripGenerationConfig {
	if x != nil {
		return x.TripGeneration
	}
	return nil
}

func (x *ModelConfigRequest) GetModeUtilities() []*ModeUtility {
	if x != nil {
		return x.ModeUtilities
	}
	return nil
}

func (x *ModelConfigRequest) GetTimePeriods() []*TimePeriod {
	if x != nil {
		return x.TimePeriods
	}
	return nil
}

// Server response for configuration
type ModelConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response code (0 = OK)
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable message
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelConfigResponse) Reset() {
	*x = ModelConfigResponse{}
	mi := &file_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelConfigResponse) ProtoMessage() {}

func (x *ModelConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelConfigResponse.ProtoReflect.Descriptor instead.
func (*ModelConfigResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9}
}

func (x *ModelConfigResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ModelConfigResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x11macro_traffic_sim\x1a\n" +
	"uuid.proto\"5\n" +
	"\tBprConfig\x12\x14\n" +
	"\x05alpha\x18\x01 \x01(\x01R\x05alpha\x12\x12\n" +
	"\x04beta\x18\x02 \x01(\x01R\x04beta\"g\n" +
	"\x15AssignmentConvergence\x12%\n" +
	"\x0emax_iterations\x18\x01 \x01(\rR\rmaxIterations\x12'\n" +
	"\x0fconvergence_gap\x18\x02 \x01(\x01R\x0econvergenceGap\"T\n" +
	"\rFurnessConfig\x12%\n" +
	"\x0emax_iterations\x18\x01 \x01(\rR\rmaxIterations\x12\x1c\n" +
	"\ttolerance\x18\x02 \x01(\x01R\ttolerance\"{\n" +
	"\x11ImpedanceFunction\x12<\n" +
	"\x04type\x18\x01 \x01(\x0e2(.macro_traffic_sim.ImpedanceFunctionTypeR\x04type\x12\x14\n" +
	"\x05alpha\x18\x02 \x01(\x01R\x05alpha\x12\x12\n" +
	"\x04beta\x18\x03 \x01(\x01R\x04beta\"\xa8\x01\n" +
	"\x10RegressionCoeffs\x12\x1c\n" +
	"\tintercept\x18\x01 \x01(\x01R\tintercept\x12\x1b\n" +
	"\tpop_coeff\x18\x02 \x01(\x01R\bpopCoeff\x12\x1b\n" +
	"\temp_coeff\x18\x03 \x01(\x01R\bempCoeff\x12\x19\n" +
	"\bhh_coeff\x18\x04 \x01(\x01R\ahhCoeff\x12!\n" +
	"\fincome_coeff\x18\x05 \x01(\x01R\vincomeCoeff\"\xc4\x04\n" +
	"\x14TripGenerationConfig\x12?\n" +
	"\x06method\x18\x01 \x01(\x0e2'.macro_traffic_sim.TripGenerationMethodR\x06method\x12P\n" +
	"\x11production_coeffs\x18\x02 \x01(\v2#.macro_traffic_sim.RegressionCoeffsR\x10productionCoeffs\x12P\n" +
	"\x11attraction_coeffs\x18\x03 \x01(\v2#.macro_traffic_sim.RegressionCoeffsR\x10attractionCoeffs\x12?\n" +
	"\x1cattraction_rate_per_employee\x18\x04 \x01(\x01R\x19attractionRatePerEmployee\x12,\n" +
	"\x12hh_size_thresholds\x18\x05 \x03(\x01R\x10hhSizeThresholds\x12+\n" +
	"\x11income_thresholds\x18\x06 \x03(\x01R\x10incomeThresholds\x12g\n" +
	"\x10production_rates\x18\a \x03(\v2<.macro_traffic_sim.TripGenerationConfig.ProductionRatesEntryR\x0fproductionRates\x1aB\n" +
	"\x14ProductionRatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x98\x01\n" +
	"\vModeUtility\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x10\n" +
	"\x03asc\x18\x02 \x01(\x01R\x03asc\x12\x1d\n" +
	"\n" +
	"coeff_time\x18\x03 \x01(\x01R\tcoeffTime\x12%\n" +
	"\x0ecoeff_distance\x18\x04 \x01(\x01R\rcoeffDistance\x12\x1d\n" +
	"\n" +
	"coeff_cost\x18\x05 \x01(\x01R\tcoeffCost\"\x7f\n" +
	"\n" +
	"TimePeriod\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"start_hour\x18\x02 \x01(\x01R\tstartHour\x12\x19\n" +
	"\bend_hour\x18\x03 \x01(\x01R\aendHour\x12#\n" +
	"\rdemand_factor\x18\x04 \x01(\x01R\fdemandFactor\"\xca\x05\n" +
	"\x12ModelConfigRequest\x128\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2\x19.macro_traffic_sim.UUIDv4R\tsessionId\x12P\n" +
	"\x11assignment_method\x18\x02 \x01(\x0e2#.macro_traffic_sim.AssignmentMethodR\x10assignmentMethod\x12.\n" +
	"\x03bpr\x18\x03 \x01(\v2\x1c.macro_traffic_sim.BprConfigR\x03bpr\x12H\n" +
	"\n" +
	"assignment\x18\x04 \x01(\v2(.macro_traffic_sim.AssignmentConvergenceR\n" +
	"assignment\x12:\n" +
	"\afurness\x18\x05 \x01(\v2 .macro_traffic_sim.FurnessConfigR\afurness\x12/\n" +
	"\x13feedback_iterations\x18\x06 \x01(\rR\x12feedbackIterations\x12\"\n" +
	"\rgp_step_scale\x18\a \x01(\x01R\vgpStepScale\x12B\n" +
	"\timpedance\x18\b \x01(\v2$.macro_traffic_sim.ImpedanceFunctionR\timpedance\x12P\n" +
	"\x0ftrip_generation\x18\t \x01(\v2'.macro_traffic_sim.TripGenerationConfigR\x0etripGeneration\x12E\n" +
	"\x0emode_utilities\x18\n" +
	" \x03(\v2\x1e.macro_traffic_sim.ModeUtilityR\rmodeUtilities\x12@\n" +
	"\ftime_periods\x18\v \x03(\v2\x1d.macro_traffic_sim.TimePeriodR\vtimePeriods\"=\n" +
	"\x13ModelConfigResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text*f\n" +
	"\x10AssignmentMethod\x12\x1a\n" +
	"\x16ASSIGNMENT_FRANK_WOLFE\x10\x00\x12\x12\n" +
	"\x0eASSIGNMENT_MSA\x10\x01\x12\"\n" +
	"\x1eASSIGNMENT_GRADIENT_PROJECTION\x10\x02*_\n" +
	"\x15ImpedanceFunctionType\x12\x19\n" +
	"\x15IMPEDANCE_EXPONENTIAL\x10\x00\x12\x13\n" +
	"\x0fIMPEDANCE_POWER\x10\x01\x12\x16\n" +
	"\x12IMPEDANCE_COMBINED\x10\x02*R\n" +
	"\x14TripGenerationMethod\x12\x17\n" +
	"\x13TRIP_GEN_REGRESSION\x10\x00\x12!\n" +
	"\x1dTRIP_GEN_CROSS_CLASSIFICATION\x10\x01B@Z>github.com/LdDl/macro_traffic_sim_grpc/clients/go;macrotrafficb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_config_proto_goTypes = []any{
	(AssignmentMethod)(0),         // 0: macro_traffic_sim.AssignmentMethod
	(ImpedanceFunctionType)(0),    // 1: macro_traffic_sim.ImpedanceFunctionType
	(TripGenerationMethod)(0),     // 2: macro_traffic_sim.TripGenerationMethod
	(*BprConfig)(nil),             // 3: macro_traffic_sim.BprConfig
	(*AssignmentConvergence)(nil), // 4: macro_traffic_sim.AssignmentConvergence
	(*FurnessConfig)(nil),         // 5: macro_traffic_sim.FurnessConfig
	(*ImpedanceFunction)(nil),     // 6: macro_traffic_sim.ImpedanceFunction
	(*RegressionCoeffs)(nil),      // 7: macro_traffic_sim.RegressionCoeffs
	(*TripGenerationConfig)(nil),  // 8: macro_traffic_sim.TripGenerationConfig
	(*ModeUtility)(nil),           // 9: macro_traffic_sim.ModeUtility
	(*TimePeriod)(nil),            // 10: macro_traffic_sim.TimePeriod
	(*ModelConfigRequest)(nil),    // 11: macro_traffic_sim.ModelConfigRequest
	(*ModelConfigResponse)(nil),   // 12: macro_traffic_sim.ModelConfigResponse
	nil,                           // 13: macro_traffic_sim.TripGenerationConfig.ProductionRatesEntry
	(*UUIDv4)(nil),                // 14: macro_traffic_sim.UUIDv4
}
var file_config_proto_depIdxs = []int32{
	1,  // 0: macro_traffic_sim.ImpedanceFunction.type:type_name -> macro_traffic_sim.ImpedanceFunctionType
	2,  // 1: macro_traffic_sim.TripGenerationConfig.method:type_name -> macro_traffic_sim.TripGenerationMethod
	7,  // 2: macro_traffic_sim.TripGenerationConfig.production_coeffs:type_name -> macro_traffic_sim.RegressionCoeffs
	7,  // 3: macro_traffic_sim.TripGenerationConfig.attraction_coeffs:type_name -> macro_traffic_sim.RegressionCoeffs
	13, // 4: macro_traffic_sim.TripGenerationConfig.production_rates:type_name -> macro_traffic_sim.TripGenerationConfig.ProductionRatesEntry
	14, // 5: macro_traffic_sim.ModelConfigRequest.session_id:type_name -> macro_traffic_sim.UUIDv4
	0,  // 6: macro_traffic_sim.ModelConfigRequest.assignment_method:type_name -> macro_traffic_sim.AssignmentMethod
	3,  // 7: macro_traffic_sim.ModelConfigRequest.bpr:type_name -> macro_traffic_sim.BprConfig
	4,  // 8: macro_traffic_sim.ModelConfigRequest.assignment:type_name -> macro_traffic_sim.AssignmentConvergence
	5,  // 9: macro_traffic_sim.ModelConfigRequest.furness:type_name -> macro_traffic_sim.FurnessConfig
	6,  // 10: macro_traffic_sim.ModelConfigRequest.impedance:type_name -> macro_traffic_sim.ImpedanceFunction
	8,  // 11: macro_traffic_sim.ModelConfigRequest.trip_generation:type_name -> macro_traffic_sim.TripGenerationConfig
	9,  // 12: macro_traffic_sim.ModelConfigRequest.mode_utilities:type_name -> macro_traffic_sim.ModeUtility
	10, // 13: macro_traffic_sim.ModelConfigRequest.time_periods:type_name -> macro_traffic_sim.TimePeriod
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	file_uuid_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		EnumInfos:         file_config_proto_enumTypes,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
