// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: network.proto

package macrotraffic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Link type classification (from OSM highway tags)
type LinkType int32

const (
	LinkType_LINK_TYPE_UNDEFINED     LinkType = 0
	LinkType_LINK_TYPE_MOTORWAY      LinkType = 1
	LinkType_LINK_TYPE_TRUNK         LinkType = 2
	LinkType_LINK_TYPE_PRIMARY       LinkType = 3
	LinkType_LINK_TYPE_SECONDARY     LinkType = 4
	LinkType_LINK_TYPE_TERTIARY      LinkType = 5
	LinkType_LINK_TYPE_RESIDENTIAL   LinkType = 6
	LinkType_LINK_TYPE_LIVING_STREET LinkType = 7
	LinkType_LINK_TYPE_SERVICE       LinkType = 8
	LinkType_LINK_TYPE_CYCLEWAY      LinkType = 9
	LinkType_LINK_TYPE_FOOTWAY       LinkType = 10
	LinkType_LINK_TYPE_TRACK         LinkType = 11
	LinkType_LINK_TYPE_UNCLASSIFIED  LinkType = 12
	LinkType_LINK_TYPE_CONNECTOR     LinkType = 13
	LinkType_LINK_TYPE_RAILWAY       LinkType = 14
	LinkType_LINK_TYPE_AEROWAY       LinkType = 15
)

// Enum value maps for LinkType.
var (
	LinkType_name = map[int32]string{
		0:  "LINK_TYPE_UNDEFINED",
		1:  "LINK_TYPE_MOTORWAY",
		2:  "LINK_TYPE_TRUNK",
		3:  "LINK_TYPE_PRIMARY",
		4:  "LINK_TYPE_SECONDARY",
		5:  "LINK_TYPE_TERTIARY",
		6:  "LINK_TYPE_RESIDENTIAL",
		7:  "LINK_TYPE_LIVING_STREET",
		8:  "LINK_TYPE_SERVICE",
		9:  "LINK_TYPE_CYCLEWAY",
		10: "LINK_TYPE_FOOTWAY",
		11: "LINK_TYPE_TRACK",
		12: "LINK_TYPE_UNCLASSIFIED",
		13: "LINK_TYPE_CONNECTOR",
		14: "LINK_TYPE_RAILWAY",
		15: "LINK_TYPE_AEROWAY",
	}
	LinkType_value = map[string]int32{
		"LINK_TYPE_UNDEFINED":     0,
		"LINK_TYPE_MOTORWAY":      1,
		"LINK_TYPE_TRUNK":         2,
		"LINK_TYPE_PRIMARY":       3,
		"LINK_TYPE_SECONDARY":     4,
		"LINK_TYPE_TERTIARY":      5,
		"LINK_TYPE_RESIDENTIAL":   6,
		"LINK_TYPE_LIVING_STREET": 7,
		"LINK_TYPE_SERVICE":       8,
		"LINK_TYPE_CYCLEWAY":      9,
		"LINK_TYPE_FOOTWAY":       10,
		"LINK_TYPE_TRACK":         11,
		"LINK_TYPE_UNCLASSIFIED":  12,
		"LINK_TYPE_CONNECTOR":     13,
		"LINK_TYPE_RAILWAY":       14,
		"LINK_TYPE_AEROWAY":       15,
	}
)

func (x LinkType) Enum() *LinkType {
	p := new(LinkType)
	*p = x
	return p
}

func (x LinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[0].Descriptor()
}

func (LinkType) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[0]
}

func (x LinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkType.Descriptor instead.
func (LinkType) EnumDescriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{0}
}

// Meso node in the transport network
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique node identifier
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// WGS84 longitude
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// WGS84 latitude
	Latitude float64 `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// Zone ID if this node is a zone centroid (>= 0). -1 otherwise.
	ZoneId int64 `protobuf:"varint,4,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	// Reference to parent macro node ID. -1 if not applicable.
	MacroNodeId int64 `protobuf:"varint,5,opt,name=macro_node_id,json=macroNodeId,proto3" json:"macro_node_id,omitempty"`
	// Reference to parent macro link ID. -1 if mid-link segment node.
	MacroLinkId   int64 `protobuf:"varint,6,opt,name=macro_link_id,json=macroLinkId,proto3" json:"macro_link_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Node) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Node) GetZoneId() int64 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *Node) GetMacroNodeId() int64 {
	if x != nil {
		return x.MacroNodeId
	}
	return 0
}

func (x *Node) GetMacroLinkId() int64 {
	if x != nil {
		return x.MacroLinkId
	}
	return 0
}

// Meso link (directed edge) in the transport network
type Link struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique link identifier
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Source node ID
	SourceNodeId int64 `protobuf:"varint,2,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	// Target node ID
	TargetNodeId int64 `protobuf:"varint,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	// Length in meters
	LengthMeters float64 `protobuf:"fixed64,4,opt,name=length_meters,json=lengthMeters,proto3" json:"length_meters,omitempty"`
	// Free-flow speed (km/h)
	FreeSpeed float64 `protobuf:"fixed64,5,opt,name=free_speed,json=freeSpeed,proto3" json:"free_speed,omitempty"`
	// Capacity (vehicles per hour per lane)
	Capacity float64 `protobuf:"fixed64,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// Number of lanes
	Lanes int32 `protobuf:"varint,7,opt,name=lanes,proto3" json:"lanes,omitempty"`
	// Road type
	LinkType LinkType `protobuf:"varint,8,opt,name=link_type,json=linkType,proto3,enum=macro_traffic_sim.LinkType" json:"link_type,omitempty"`
	// Whether this is a connection (turn) link
	IsConnection bool `protobuf:"varint,9,opt,name=is_connection,json=isConnection,proto3" json:"is_connection,omitempty"`
	// Reference to parent macro link. -1 if not applicable.
	MacroLinkId int64 `protobuf:"varint,10,opt,name=macro_link_id,json=macroLinkId,proto3" json:"macro_link_id,omitempty"`
	// Reference to movement ID. -1 if not a connection link.
	MovementId    int64 `protobuf:"varint,11,opt,name=movement_id,json=movementId,proto3" json:"movement_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{1}
}

func (x *Link) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Link) GetSourceNodeId() int64 {
	if x != nil {
		return x.SourceNodeId
	}
	return 0
}

func (x *Link) GetTargetNodeId() int64 {
	if x != nil {
		return x.TargetNodeId
	}
	return 0
}

func (x *Link) GetLengthMeters() float64 {
	if x != nil {
		return x.LengthMeters
	}
	return 0
}

func (x *Link) GetFreeSpeed() float64 {
	if x != nil {
		return x.FreeSpeed
	}
	return 0
}

func (x *Link) GetCapacity() float64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Link) GetLanes() int32 {
	if x != nil {
		return x.Lanes
	}
	return 0
}

func (x *Link) GetLinkType() LinkType {
	if x != nil {
		return x.LinkType
	}
	return LinkType_LINK_TYPE_UNDEFINED
}

func (x *Link) GetIsConnection() bool {
	if x != nil {
		return x.IsConnection
	}
	return false
}

func (x *Link) GetMacroLinkId() int64 {
	if x != nil {
		return x.MacroLinkId
	}
	return 0
}

func (x *Link) GetMovementId() int64 {
	if x != nil {
		return x.MovementId
	}
	return 0
}

// Zone (TAZ) with socioeconomic attributes
type Zone struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique zone identifier
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Zone name or description
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Total population
	Population float64 `protobuf:"fixed64,3,opt,name=population,proto3" json:"population,omitempty"`
	// Total employment (jobs)
	Employment float64 `protobuf:"fixed64,4,opt,name=employment,proto3" json:"employment,omitempty"`
	// Number of households
	Households float64 `protobuf:"fixed64,5,opt,name=households,proto3" json:"households,omitempty"`
	// Average household income
	AvgIncome float64 `protobuf:"fixed64,6,opt,name=avg_income,json=avgIncome,proto3" json:"avg_income,omitempty"`
	// Area in square kilometers
	AreaSqKm      float64 `protobuf:"fixed64,7,opt,name=area_sq_km,json=areaSqKm,proto3" json:"area_sq_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zone) Reset() {
	*x = Zone{}
	mi := &file_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{2}
}

func (x *Zone) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Zone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Zone) GetPopulation() float64 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *Zone) GetEmployment() float64 {
	if x != nil {
		return x.Employment
	}
	return 0
}

func (x *Zone) GetHouseholds() float64 {
	if x != nil {
		return x.Households
	}
	return 0
}

func (x *Zone) GetAvgIncome() float64 {
	if x != nil {
		return x.AvgIncome
	}
	return 0
}

func (x *Zone) GetAreaSqKm() float64 {
	if x != nil {
		return x.AreaSqKm
	}
	return 0
}

// Network data chunk (nodes + links). Streamed in batches of up to 10000 entities.
type NetworkChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session identifier
	SessionId *UUIDv4 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Node data batch
	Nodes []*Node `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// Link data batch
	Links         []*Link `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkChunk) Reset() {
	*x = NetworkChunk{}
	mi := &file_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkChunk) ProtoMessage() {}

func (x *NetworkChunk) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkChunk.ProtoReflect.Descriptor instead.
func (*NetworkChunk) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkChunk) GetSessionId() *UUIDv4 {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *NetworkChunk) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *NetworkChunk) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

// Server response for network ingest
type NetworkChunkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response code (0 = OK)
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable message
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Cumulative counts
	NodesReceived uint32 `protobuf:"varint,3,opt,name=nodes_received,json=nodesReceived,proto3" json:"nodes_received,omitempty"`
	LinksReceived uint32 `protobuf:"varint,4,opt,name=links_received,json=linksReceived,proto3" json:"links_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkChunkResponse) Reset() {
	*x = NetworkChunkResponse{}
	mi := &file_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkChunkResponse) ProtoMessage() {}

func (x *NetworkChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkChunkResponse.ProtoReflect.Descriptor instead.
func (*NetworkChunkResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkChunkResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NetworkChunkResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *NetworkChunkResponse) GetNodesReceived() uint32 {
	if x != nil {
		return x.NodesReceived
	}
	return 0
}

func (x *NetworkChunkResponse) GetLinksReceived() uint32 {
	if x != nil {
		return x.LinksReceived
	}
	return 0
}

// Zone data chunk. Streamed in batches.
type ZoneChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session identifier
	SessionId *UUIDv4 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Zone data batch
	Zones         []*Zone `protobuf:"bytes,2,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneChunk) Reset() {
	*x = ZoneChunk{}
	mi := &file_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneChunk) ProtoMessage() {}

func (x *ZoneChunk) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneChunk.ProtoReflect.Descriptor instead.
func (*ZoneChunk) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{5}
}

func (x *ZoneChunk) GetSessionId() *UUIDv4 {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *ZoneChunk) GetZones() []*Zone {
	if x != nil {
		return x.Zones
	}
	return nil
}

// Server response for zone ingest
type ZoneChunkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response code (0 = OK)
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable message
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Cumulative count
	ZonesReceived uint32 `protobuf:"varint,3,opt,name=zones_received,json=zonesReceived,proto3" json:"zones_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneChunkResponse) Reset() {
	*x = ZoneChunkResponse{}
	mi := &file_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneChunkResponse) ProtoMessage() {}

func (x *ZoneChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneChunkResponse.ProtoReflect.Descriptor instead.
func (*ZoneChunkResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{6}
}

func (x *ZoneChunkResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ZoneChunkResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ZoneChunkResponse) GetZonesReceived() uint32 {
	if x != nil {
		return x.ZonesReceived
	}
	return 0
}

// OD matrix data chunk. First chunk must include zone_ids.
type OdMatrixChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session identifier
	SessionId *UUIDv4 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Ordered zone IDs (sent once in first chunk)
	ZoneIds []int64 `protobuf:"varint,2,rep,packed,name=zone_ids,json=zoneIds,proto3" json:"zone_ids,omitempty"`
	// Row-major flat data (chunked across messages)
	Data          []float64 `protobuf:"fixed64,3,rep,packed,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OdMatrixChunk) Reset() {
	*x = OdMatrixChunk{}
	mi := &file_network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OdMatrixChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdMatrixChunk) ProtoMessage() {}

func (x *OdMatrixChunk) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdMatrixChunk.ProtoReflect.Descriptor instead.
func (*OdMatrixChunk) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{7}
}

func (x *OdMatrixChunk) GetSessionId() *UUIDv4 {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *OdMatrixChunk) GetZoneIds() []int64 {
	if x != nil {
		return x.ZoneIds
	}
	return nil
}

func (x *OdMatrixChunk) GetData() []float64 {
	if x != nil {
		return x.Data
	}
	return nil
}

// Server response for OD matrix ingest
type OdMatrixChunkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response code (0 = OK)
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable message
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Number of cells received so far
	CellsReceived uint64 `protobuf:"varint,3,opt,name=cells_received,json=cellsReceived,proto3" json:"cells_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OdMatrixChunkResponse) Reset() {
	*x = OdMatrixChunkResponse{}
	mi := &file_network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OdMatrixChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OdMatrixChunkResponse) ProtoMessage() {}

func (x *OdMatrixChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OdMatrixChunkResponse.ProtoReflect.Descriptor instead.
func (*OdMatrixChunkResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{8}
}

func (x *OdMatrixChunkResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OdMatrixChunkResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OdMatrixChunkResponse) GetCellsReceived() uint64 {
	if x != nil {
		return x.CellsReceived
	}
	return 0
}

var File_network_proto protoreflect.FileDescriptor

const file_network_proto_rawDesc = "" +
	"\n" +
	"\rnetwork.proto\x12\x11macro_traffic_sim\x1a\n" +
	"uuid.proto\"\xb1\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x17\n" +
	"\azone_id\x18\x04 \x01(\x03R\x06zoneId\x12\"\n" +
	"\rmacro_node_id\x18\x05 \x01(\x03R\vmacroNodeId\x12\"\n" +
	"\rmacro_link_id\x18\x06 \x01(\x03R\vmacroLinkId\"\xfc\x02\n" +
	"\x04Link\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12$\n" +
	"\x0esource_node_id\x18\x02 \x01(\x03R\fsourceNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x03 \x01(\x03R\ftargetNodeId\x12#\n" +
	"\rlength_meters\x18\x04 \x01(\x01R\flengthMeters\x12\x1d\n" +
	"\n" +
	"free_speed\x18\x05 \x01(\x01R\tfreeSpeed\x12\x1a\n" +
	"\bcapacity\x18\x06 \x01(\x01R\bcapacity\x12\x14\n" +
	"\x05lanes\x18\a \x01(\x05R\x05lanes\x128\n" +
	"\tlink_type\x18\b \x01(\x0e2\x1b.macro_traffic_sim.LinkTypeR\blinkType\x12#\n" +
	"\ris_connection\x18\t \x01(\bR\fisConnection\x12\"\n" +
	"\rmacro_link_id\x18\n" +
	" \x01(\x03R\vmacroLinkId\x12\x1f\n" +
	"\vmovement_id\x18\v \x01(\x03R\n" +
	"movementId\"\xc7\x01\n" +
	"\x04Zone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"population\x18\x03 \x01(\x01R\n" +
	"population\x12\x1e\n" +
	"\n" +
	"employment\x18\x04 \x01(\x01R\n" +
	"employment\x12\x1e\n" +
	"\n" +
	"households\x18\x05 \x01(\x01R\n" +
	"households\x12\x1d\n" +
	"\n" +
	"avg_income\x18\x06 \x01(\x01R\tavgIncome\x12\x1c\n" +
	"\n" +
	"area_sq_km\x18\a \x01(\x01R\bareaSqKm\"\xa6\x01\n" +
	"\fNetworkChunk\x128\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2\x19.macro_traffic_sim.UUIDv4R\tsessionId\x12-\n" +
	"\x05nodes\x18\x02 \x03(\v2\x17.macro_traffic_sim.NodeR\x05nodes\x12-\n" +
	"\x05links\x18\x03 \x03(\v2\x17.macro_traffic_sim.LinkR\x05links\"\x8c\x01\n" +
	"\x14NetworkChunkResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12%\n" +
	"\x0enodes_received\x18\x03 \x01(\rR\rnodesReceived\x12%\n" +
	"\x0elinks_received\x18\x04 \x01(\rR\rlinksReceived\"t\n" +
	"\tZoneChunk\x128\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2\x19.macro_traffic_sim.UUIDv4R\tsessionId\x12-\n" +
	"\x05zones\x18\x02 \x03(\v2\x17.macro_traffic_sim.ZoneR\x05zones\"b\n" +
	"\x11ZoneChunkResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12%\n" +
	"\x0ezones_received\x18\x03 \x01(\rR\rzonesReceived\"x\n" +
	"\rOdMatrixChunk\x128\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2\x19.macro_traffic_sim.UUIDv4R\tsessionId\x12\x19\n" +
	"\bzone_ids\x18\x02 \x03(\x03R\azoneIds\x12\x12\n" +
	"\x04data\x18\x03 \x03(\x01R\x04data\"f\n" +
	"\x15OdMatrixChunkResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12%\n" +
	"\x0ecells_received\x18\x03 \x01(\x04R\rcellsReceived*\x8e\x03\n" +
	"\bLinkType\x12\x17\n" +
	"\x13LINK_TYPE_UNDEFINED\x10\x00\x12\x16\n" +
	"\x12LINK_TYPE_MOTORWAY\x10\x01\x12\x13\n" +
	"\x0fLINK_TYPE_TRUNK\x10\x02\x12\x15\n" +
	"\x11LINK_TYPE_PRIMARY\x10\x03\x12\x17\n" +
	"\x13LINK_TYPE_SECONDARY\x10\x04\x12\x16\n" +
	"\x12LINK_TYPE_TERTIARY\x10\x05\x12\x19\n" +
	"\x15LINK_TYPE_RESIDENTIAL\x10\x06\x12\x1b\n" +
	"\x17LINK_TYPE_LIVING_STREET\x10\a\x12\x15\n" +
	"\x11LINK_TYPE_SERVICE\x10\b\x12\x16\n" +
	"\x12LINK_TYPE_CYCLEWAY\x10\t\x12\x15\n" +
	"\x11LINK_TYPE_FOOTWAY\x10\n" +
	"\x12\x13\n" +
	"\x0fLINK_TYPE_TRACK\x10\v\x12\x1a\n" +
	"\x16LINK_TYPE_UNCLASSIFIED\x10\f\x12\x17\n" +
	"\x13LINK_TYPE_CONNECTOR\x10\r\x12\x15\n" +
	"\x11LINK_TYPE_RAILWAY\x10\x0e\x12\x15\n" +
	"\x11LINK_TYPE_AEROWAY\x10\x0fB@Z>github.com/LdDl/macro_traffic_sim_grpc/clients/go;macrotrafficb\x06proto3"

var (
	file_network_proto_rawDescOnce sync.Once
	file_network_proto_rawDescData []byte
)

func file_network_proto_rawDescGZIP() []byte {
	file_network_proto_rawDescOnce.Do(func() {
		file_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)))
	})
	return file_network_proto_rawDescData
}

var file_network_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_network_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_network_proto_goTypes = []any{
	(LinkType)(0),                 // 0: macro_traffic_sim.LinkType
	(*Node)(nil),                  // 1: macro_traffic_sim.Node
	(*Link)(nil),                  // 2: macro_traffic_sim.Link
	(*Zone)(nil),                  // 3: macro_traffic_sim.Zone
	(*NetworkChunk)(nil),          // 4: macro_traffic_sim.NetworkChunk
	(*NetworkChunkResponse)(nil),  // 5: macro_traffic_sim.NetworkChunkResponse
	(*ZoneChunk)(nil),             // 6: macro_traffic_sim.ZoneChunk
	(*ZoneChunkResponse)(nil),     // 7: macro_traffic_sim.ZoneChunkResponse
	(*OdMatrixChunk)(nil),         // 8: macro_traffic_sim.OdMatrixChunk
	(*OdMatrixChunkResponse)(nil), // 9: macro_traffic_sim.OdMatrixChunkResponse
	(*UUIDv4)(nil),                // 10: macro_traffic_sim.UUIDv4
}
var file_network_proto_depIdxs = []int32{
	0,  // 0: macro_traffic_sim.Link.link_type:type_name -> macro_traffic_sim.LinkType
	10, // 1: macro_traffic_sim.NetworkChunk.session_id:type_name -> macro_traffic_sim.UUIDv4
	1,  // 2: macro_traffic_sim.NetworkChunk.nodes:type_name -> macro_traffic_sim.Node
	2,  // 3: macro_traffic_sim.NetworkChunk.links:type_name -> macro_traffic_sim.Link
	10, // 4: macro_traffic_sim.ZoneChunk.session_id:type_name -> macro_traffic_sim.UUIDv4
	3,  // 5: macro_traffic_sim.ZoneChunk.zones:type_name -> macro_traffic_sim.Zone
	10, // 6: macro_traffic_sim.OdMatrixChunk.session_id:type_name -> macro_traffic_sim.UUIDv4
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_network_proto_init() }
func file_network_proto_init() {
	if File_network_proto != nil {
		return
	}
	file_uuid_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_network_proto_goTypes,
		DependencyIndexes: file_network_proto_depIdxs,
		EnumInfos:         file_network_proto_enumTypes,
		MessageInfos:      file_network_proto_msgTypes,
	}.Build()
	File_network_proto = out.File
	file_network_proto_goTypes = nil
	file_network_proto_depIdxs = nil
}
