// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: run.proto

package macrotraffic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to run the 4-step pipeline
type RunPipelineRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session identifier
	SessionId     *UUIDv4 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPipelineRequest) Reset() {
	*x = RunPipelineRequest{}
	mi := &file_run_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPipelineRequest) ProtoMessage() {}

func (x *RunPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPipelineRequest.ProtoReflect.Descriptor instead.
func (*RunPipelineRequest) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{0}
}

func (x *RunPipelineRequest) GetSessionId() *UUIDv4 {
	if x != nil {
		return x.SessionId
	}
	return nil
}

// Progress event streamed during pipeline execution
type RunPipelineProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response code (0 = OK)
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable message
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Session identifier
	SessionId *UUIDv4 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Current pipeline phase
	Phase string `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"` // "generation", "distribution", "mode_choice", "assignment"
	// Multi-period progress
	PeriodCurrent uint32 `protobuf:"varint,5,opt,name=period_current,json=periodCurrent,proto3" json:"period_current,omitempty"` // 1-based
	PeriodTotal   uint32 `protobuf:"varint,6,opt,name=period_total,json=periodTotal,proto3" json:"period_total,omitempty"`
	// Feedback loop progress
	FeedbackCurrent uint32 `protobuf:"varint,7,opt,name=feedback_current,json=feedbackCurrent,proto3" json:"feedback_current,omitempty"` // 1-based
	FeedbackTotal   uint32 `protobuf:"varint,8,opt,name=feedback_total,json=feedbackTotal,proto3" json:"feedback_total,omitempty"`
	// Assignment iteration detail
	AssignmentIteration     uint32  `protobuf:"varint,9,opt,name=assignment_iteration,json=assignmentIteration,proto3" json:"assignment_iteration,omitempty"`
	AssignmentMaxIterations uint32  `protobuf:"varint,10,opt,name=assignment_max_iterations,json=assignmentMaxIterations,proto3" json:"assignment_max_iterations,omitempty"`
	RelativeGap             float64 `protobuf:"fixed64,11,opt,name=relative_gap,json=relativeGap,proto3" json:"relative_gap,omitempty"`
	// Completion flags
	IsCompleted   bool   `protobuf:"varint,12,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	IsFailed      bool   `protobuf:"varint,13,opt,name=is_failed,json=isFailed,proto3" json:"is_failed,omitempty"`
	ErrorMessage  string `protobuf:"bytes,14,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPipelineProgress) Reset() {
	*x = RunPipelineProgress{}
	mi := &file_run_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPipelineProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPipelineProgress) ProtoMessage() {}

func (x *RunPipelineProgress) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPipelineProgress.ProtoReflect.Descriptor instead.
func (*RunPipelineProgress) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{1}
}

func (x *RunPipelineProgress) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RunPipelineProgress) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RunPipelineProgress) GetSessionId() *UUIDv4 {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *RunPipelineProgress) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *RunPipelineProgress) GetPeriodCurrent() uint32 {
	if x != nil {
		return x.PeriodCurrent
	}
	return 0
}

func (x *RunPipelineProgress) GetPeriodTotal() uint32 {
	if x != nil {
		return x.PeriodTotal
	}
	return 0
}

func (x *RunPipelineProgress) GetFeedbackCurrent() uint32 {
	if x != nil {
		return x.FeedbackCurrent
	}
	return 0
}

func (x *RunPipelineProgress) GetFeedbackTotal() uint32 {
	if x != nil {
		return x.FeedbackTotal
	}
	return 0
}

func (x *RunPipelineProgress) GetAssignmentIteration() uint32 {
	if x != nil {
		return x.AssignmentIteration
	}
	return 0
}

func (x *RunPipelineProgress) GetAssignmentMaxIterations() uint32 {
	if x != nil {
		return x.AssignmentMaxIterations
	}
	return 0
}

func (x *RunPipelineProgress) GetRelativeGap() float64 {
	if x != nil {
		return x.RelativeGap
	}
	return 0
}

func (x *RunPipelineProgress) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *RunPipelineProgress) GetIsFailed() bool {
	if x != nil {
		return x.IsFailed
	}
	return false
}

func (x *RunPipelineProgress) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_run_proto protoreflect.FileDescriptor

const file_run_proto_rawDesc = "" +
	"\n" +
	"\trun.proto\x12\x11macro_traffic_sim\x1a\n" +
	"uuid.proto\"N\n" +
	"\x12RunPipelineRequest\x128\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2\x19.macro_traffic_sim.UUIDv4R\tsessionId\"\xa0\x04\n" +
	"\x13RunPipelineProgress\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x128\n" +
	"\n" +
	"session_id\x18\x03 \x01(\v2\x19.macro_traffic_sim.UUIDv4R\tsessionId\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12%\n" +
	"\x0eperiod_current\x18\x05 \x01(\rR\rperiodCurrent\x12!\n" +
	"\fperiod_total\x18\x06 \x01(\rR\vperiodTotal\x12)\n" +
	"\x10feedback_current\x18\a \x01(\rR\x0ffeedbackCurrent\x12%\n" +
	"\x0efeedback_total\x18\b \x01(\rR\rfeedbackTotal\x121\n" +
	"\x14assignment_iteration\x18\t \x01(\rR\x13assignmentIteration\x12:\n" +
	"\x19assignment_max_iterations\x18\n" +
	" \x01(\rR\x17assignmentMaxIterations\x12!\n" +
	"\frelative_gap\x18\v \x01(\x01R\vrelativeGap\x12!\n" +
	"\fis_completed\x18\f \x01(\bR\visCompleted\x12\x1b\n" +
	"\tis_failed\x18\r \x01(\bR\bisFailed\x12#\n" +
	"\rerror_message\x18\x0e \x01(\tR\ferrorMessageB@Z>github.com/LdDl/macro_traffic_sim_grpc/clients/go;macrotrafficb\x06proto3"

var (
	file_run_proto_rawDescOnce sync.Once
	file_run_proto_rawDescData []byte
)

func file_run_proto_rawDescGZIP() []byte {
	file_run_proto_rawDescOnce.Do(func() {
		file_run_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_run_proto_rawDesc), len(file_run_proto_rawDesc)))
	})
	return file_run_proto_rawDescData
}

var file_run_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_run_proto_goTypes = []any{
	(*RunPipelineRequest)(nil),  // 0: macro_traffic_sim.RunPipelineRequest
	(*RunPipelineProgress)(nil), // 1: macro_traffic_sim.RunPipelineProgress
	(*UUIDv4)(nil),              // 2: macro_traffic_sim.UUIDv4
}
var file_run_proto_depIdxs = []int32{
	2, // 0: macro_traffic_sim.RunPipelineRequest.session_id:type_name -> macro_traffic_sim.UUIDv4
	2, // 1: macro_traffic_sim.RunPipelineProgress.session_id:type_name -> macro_traffic_sim.UUIDv4
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_run_proto_init() }
func file_run_proto_init() {
	if File_run_proto != nil {
		return
	}
	file_uuid_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_run_proto_rawDesc), len(file_run_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_run_proto_goTypes,
		DependencyIndexes: file_run_proto_depIdxs,
		MessageInfos:      file_run_proto_msgTypes,
	}.Build()
	File_run_proto = out.File
	file_run_proto_goTypes = nil
	file_run_proto_depIdxs = nil
}
