// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: service.proto

package macrotraffic

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MacroService_NewSession_FullMethodName        = "/macro_traffic_sim.MacroService/NewSession"
	MacroService_InfoSession_FullMethodName       = "/macro_traffic_sim.MacroService/InfoSession"
	MacroService_DeleteSession_FullMethodName     = "/macro_traffic_sim.MacroService/DeleteSession"
	MacroService_PushNetwork_FullMethodName       = "/macro_traffic_sim.MacroService/PushNetwork"
	MacroService_PushZones_FullMethodName         = "/macro_traffic_sim.MacroService/PushZones"
	MacroService_PushOdMatrix_FullMethodName      = "/macro_traffic_sim.MacroService/PushOdMatrix"
	MacroService_SetModelConfig_FullMethodName    = "/macro_traffic_sim.MacroService/SetModelConfig"
	MacroService_RunPipeline_FullMethodName       = "/macro_traffic_sim.MacroService/RunPipeline"
	MacroService_GetLinkVolumes_FullMethodName    = "/macro_traffic_sim.MacroService/GetLinkVolumes"
	MacroService_GetSkimMatrix_FullMethodName     = "/macro_traffic_sim.MacroService/GetSkimMatrix"
	MacroService_GetOdResult_FullMethodName       = "/macro_traffic_sim.MacroService/GetOdResult"
	MacroService_GetAssignmentInfo_FullMethodName = "/macro_traffic_sim.MacroService/GetAssignmentInfo"
)

// MacroServiceClient is the client API for MacroService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MacroServiceClient interface {
	// Session management
	NewSession(ctx context.Context, in *NewSessionRequest, opts ...grpc.CallOption) (*NewSessionResponse, error)
	InfoSession(ctx context.Context, in *SessionId, opts ...grpc.CallOption) (*InfoSessionResponse, error)
	DeleteSession(ctx context.Context, in *SessionId, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	// Network data loading (bidirectional streaming for large networks)
	PushNetwork(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NetworkChunk, NetworkChunkResponse], error)
	PushZones(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ZoneChunk, ZoneChunkResponse], error)
	PushOdMatrix(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OdMatrixChunk, OdMatrixChunkResponse], error)
	// Model configuration
	SetModelConfig(ctx context.Context, in *ModelConfigRequest, opts ...grpc.CallOption) (*ModelConfigResponse, error)
	// Pipeline execution (server-streaming for progress)
	RunPipeline(ctx context.Context, in *RunPipelineRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunPipelineProgress], error)
	// Results retrieval (server-streaming for large data)
	GetLinkVolumes(ctx context.Context, in *LinkVolumesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LinkVolumesChunk], error)
	GetSkimMatrix(ctx context.Context, in *SkimRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SkimMatrixChunk], error)
	GetOdResult(ctx context.Context, in *OdResultRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OdResultChunk], error)
	GetAssignmentInfo(ctx context.Context, in *AssignmentInfoRequest, opts ...grpc.CallOption) (*AssignmentInfoResponse, error)
}

type macroServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMacroServiceClient(cc grpc.ClientConnInterface) MacroServiceClient {
	return &macroServiceClient{cc}
}

func (c *macroServiceClient) NewSession(ctx context.Context, in *NewSessionRequest, opts ...grpc.CallOption) (*NewSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewSessionResponse)
	err := c.cc.Invoke(ctx, MacroService_NewSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroServiceClient) InfoSession(ctx context.Context, in *SessionId, opts ...grpc.CallOption) (*InfoSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoSessionResponse)
	err := c.cc.Invoke(ctx, MacroService_InfoSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroServiceClient) DeleteSession(ctx context.Context, in *SessionId, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, MacroService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroServiceClient) PushNetwork(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NetworkChunk, NetworkChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MacroService_ServiceDesc.Streams[0], MacroService_PushNetwork_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NetworkChunk, NetworkChunkResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MacroService_PushNetworkClient = grpc.BidiStreamingClient[NetworkChunk, NetworkChunkResponse]

func (c *macroServiceClient) PushZones(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ZoneChunk, ZoneChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MacroService_ServiceDesc.Streams[1], MacroService_PushZones_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ZoneChunk, ZoneChunkResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MacroService_PushZonesClient = grpc.BidiStreamingClient[ZoneChunk, ZoneChunkResponse]

func (c *macroServiceClient) PushOdMatrix(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OdMatrixChunk, OdMatrixChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MacroService_ServiceDesc.Streams[2], MacroService_PushOdMatrix_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OdMatrixChunk, OdMatrixChunkResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MacroService_PushOdMatrixClient = grpc.BidiStreamingClient[OdMatrixChunk, OdMatrixChunkResponse]

func (c *macroServiceClient) SetModelConfig(ctx context.Context, in *ModelConfigRequest, opts ...grpc.CallOption) (*ModelConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelConfigResponse)
	err := c.cc.Invoke(ctx, MacroService_SetModelConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroServiceClient) RunPipeline(ctx context.Context, in *RunPipelineRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunPipelineProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MacroService_ServiceDesc.Streams[3], MacroService_RunPipeline_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunPipelineRequest, RunPipelineProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MacroService_RunPipelineClient = grpc.ServerStreamingClient[RunPipelineProgress]

func (c *macroServiceClient) GetLinkVolumes(ctx context.Context, in *LinkVolumesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LinkVolumesChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MacroService_ServiceDesc.Streams[4], MacroService_GetLinkVolumes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LinkVolumesRequest, LinkVolumesChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MacroService_GetLinkVolumesClient = grpc.ServerStreamingClient[LinkVolumesChunk]

func (c *macroServiceClient) GetSkimMatrix(ctx context.Context, in *SkimRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SkimMatrixChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MacroService_ServiceDesc.Streams[5], MacroService_GetSkimMatrix_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SkimRequest, SkimMatrixChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MacroService_GetSkimMatrixClient = grpc.ServerStreamingClient[SkimMatrixChunk]

func (c *macroServiceClient) GetOdResult(ctx context.Context, in *OdResultRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OdResultChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MacroService_ServiceDesc.Streams[6], MacroService_GetOdResult_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OdResultRequest, OdResultChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MacroService_GetOdResultClient = grpc.ServerStreamingClient[OdResultChunk]

func (c *macroServiceClient) GetAssignmentInfo(ctx context.Context, in *AssignmentInfoRequest, opts ...grpc.CallOption) (*AssignmentInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignmentInfoResponse)
	err := c.cc.Invoke(ctx, MacroService_GetAssignmentInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MacroServiceServer is the server API for MacroService service.
// All implementations must embed UnimplementedMacroServiceServer
// for forward compatibility.
type MacroServiceServer interface {
	// Session management
	NewSession(context.Context, *NewSessionRequest) (*NewSessionResponse, error)
	InfoSession(context.Context, *SessionId) (*InfoSessionResponse, error)
	DeleteSession(context.Context, *SessionId) (*DeleteSessionResponse, error)
	// Network data loading (bidirectional streaming for large networks)
	PushNetwork(grpc.BidiStreamingServer[NetworkChunk, NetworkChunkResponse]) error
	PushZones(grpc.BidiStreamingServer[ZoneChunk, ZoneChunkResponse]) error
	PushOdMatrix(grpc.BidiStreamingServer[OdMatrixChunk, OdMatrixChunkResponse]) error
	// Model configuration
	SetModelConfig(context.Context, *ModelConfigRequest) (*ModelConfigResponse, error)
	// Pipeline execution (server-streaming for progress)
	RunPipeline(*RunPipelineRequest, grpc.ServerStreamingServer[RunPipelineProgress]) error
	// Results retrieval (server-streaming for large data)
	GetLinkVolumes(*LinkVolumesRequest, grpc.ServerStreamingServer[LinkVolumesChunk]) error
	GetSkimMatrix(*SkimRequest, grpc.ServerStreamingServer[SkimMatrixChunk]) error
	GetOdResult(*OdResultRequest, grpc.ServerStreamingServer[OdResultChunk]) error
	GetAssignmentInfo(context.Context, *AssignmentInfoRequest) (*AssignmentInfoResponse, error)
	mustEmbedUnimplementedMacroServiceServer()
}

// UnimplementedMacroServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMacroServiceServer struct{}

func (UnimplementedMacroServiceServer) NewSession(context.Context, *NewSessionRequest) (*NewSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewSession not implemented")
}
func (UnimplementedMacroServiceServer) InfoSession(context.Context, *SessionId) (*InfoSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InfoSession not implemented")
}
func (UnimplementedMacroServiceServer) DeleteSession(context.Context, *SessionId) (*DeleteSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedMacroServiceServer) PushNetwork(grpc.BidiStreamingServer[NetworkChunk, NetworkChunkResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PushNetwork not implemented")
}
func (UnimplementedMacroServiceServer) PushZones(grpc.BidiStreamingServer[ZoneChunk, ZoneChunkResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PushZones not implemented")
}
func (UnimplementedMacroServiceServer) PushOdMatrix(grpc.BidiStreamingServer[OdMatrixChunk, OdMatrixChunkResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PushOdMatrix not implemented")
}
func (UnimplementedMacroServiceServer) SetModelConfig(context.Context, *ModelConfigRequest) (*ModelConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetModelConfig not implemented")
}
func (UnimplementedMacroServiceServer) RunPipeline(*RunPipelineRequest, grpc.ServerStreamingServer[RunPipelineProgress]) error {
	return status.Errorf(codes.Unimplemented, "method RunPipeline not implemented")
}
func (UnimplementedMacroServiceServer) GetLinkVolumes(*LinkVolumesRequest, grpc.ServerStreamingServer[LinkVolumesChunk]) error {
	return status.Errorf(codes.Unimplemented, "method GetLinkVolumes not implemented")
}
func (UnimplementedMacroServiceServer) GetSkimMatrix(*SkimRequest, grpc.ServerStreamingServer[SkimMatrixChunk]) error {
	return status.Errorf(codes.Unimplemented, "method GetSkimMatrix not implemented")
}
func (UnimplementedMacroServiceServer) GetOdResult(*OdResultRequest, grpc.ServerStreamingServer[OdResultChunk]) error {
	return status.Errorf(codes.Unimplemented, "method GetOdResult not implemented")
}
func (UnimplementedMacroServiceServer) GetAssignmentInfo(context.Context, *AssignmentInfoRequest) (*AssignmentInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssignmentInfo not implemented")
}
func (UnimplementedMacroServiceServer) mustEmbedUnimplementedMacroServiceServer() {}
func (UnimplementedMacroServiceServer) testEmbeddedByValue()                      {}

// UnsafeMacroServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MacroServiceServer will
// result in compilation errors.
type UnsafeMacroServiceServer interface {
	mustEmbedUnimplementedMacroServiceServer()
}

func RegisterMacroServiceServer(s grpc.ServiceRegistrar, srv MacroServiceServer) {
	// If the following call pancis, it indicates UnimplementedMacroServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MacroService_ServiceDesc, srv)
}

func _MacroService_NewSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroServiceServer).NewSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroService_NewSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroServiceServer).NewSession(ctx, req.(*NewSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroService_InfoSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroServiceServer).InfoSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroService_InfoSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroServiceServer).InfoSession(ctx, req.(*SessionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroServiceServer).DeleteSession(ctx, req.(*SessionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroService_PushNetwork_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MacroServiceServer).PushNetwork(&grpc.GenericServerStream[NetworkChunk, NetworkChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MacroService_PushNetworkServer = grpc.BidiStreamingServer[NetworkChunk, NetworkChunkResponse]

func _MacroService_PushZones_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MacroServiceServer).PushZones(&grpc.GenericServerStream[ZoneChunk, ZoneChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MacroService_PushZonesServer = grpc.BidiStreamingServer[ZoneChunk, ZoneChunkResponse]

func _MacroService_PushOdMatrix_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MacroServiceServer).PushOdMatrix(&grpc.GenericServerStream[OdMatrixChunk, OdMatrixChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MacroService_PushOdMatrixServer = grpc.BidiStreamingServer[OdMatrixChunk, OdMatrixChunkResponse]

func _MacroService_SetModelConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroServiceServer).SetModelConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroService_SetModelConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroServiceServer).SetModelConfig(ctx, req.(*ModelConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroService_RunPipeline_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunPipelineRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MacroServiceServer).RunPipeline(m, &grpc.GenericServerStream[RunPipelineRequest, RunPipelineProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MacroService_RunPipelineServer = grpc.ServerStreamingServer[RunPipelineProgress]

func _MacroService_GetLinkVolumes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LinkVolumesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MacroServiceServer).GetLinkVolumes(m, &grpc.GenericServerStream[LinkVolumesRequest, LinkVolumesChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MacroService_GetLinkVolumesServer = grpc.ServerStreamingServer[LinkVolumesChunk]

func _MacroService_GetSkimMatrix_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SkimRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MacroServiceServer).GetSkimMatrix(m, &grpc.GenericServerStream[SkimRequest, SkimMatrixChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MacroService_GetSkimMatrixServer = grpc.ServerStreamingServer[SkimMatrixChunk]

func _MacroService_GetOdResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OdResultRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MacroServiceServer).GetOdResult(m, &grpc.GenericServerStream[OdResultRequest, OdResultChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MacroService_GetOdResultServer = grpc.ServerStreamingServer[OdResultChunk]

func _MacroService_GetAssignmentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignmentInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroServiceServer).GetAssignmentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroService_GetAssignmentInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroServiceServer).GetAssignmentInfo(ctx, req.(*AssignmentInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MacroService_ServiceDesc is the grpc.ServiceDesc for MacroService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MacroService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "macro_traffic_sim.MacroService",
	HandlerType: (*MacroServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewSession",
			Handler:    _MacroService_NewSession_Handler,
		},
		{
			MethodName: "InfoSession",
			Handler:    _MacroService_InfoSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _MacroService_DeleteSession_Handler,
		},
		{
			MethodName: "SetModelConfig",
			Handler:    _MacroService_SetModelConfig_Handler,
		},
		{
			MethodName: "GetAssignmentInfo",
			Handler:    _MacroService_GetAssignmentInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushNetwork",
			Handler:       _MacroService_PushNetwork_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PushZones",
			Handler:       _MacroService_PushZones_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PushOdMatrix",
			Handler:       _MacroService_PushOdMatrix_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RunPipeline",
			Handler:       _MacroService_RunPipeline_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetLinkVolumes",
			Handler:       _MacroService_GetLinkVolumes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetSkimMatrix",
			Handler:       _MacroService_GetSkimMatrix_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetOdResult",
			Handler:       _MacroService_GetOdResult_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
