// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: service.proto

package macrotraffic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x11macro_traffic_sim\x1a\n" +
	"uuid.proto\x1a\rsession.proto\x1a\rnetwork.proto\x1a\fconfig.proto\x1a\trun.proto\x1a\rresults.proto2\xfa\b\n" +
	"\fMacroService\x12[\n" +
	"\n" +
	"NewSession\x12$.macro_traffic_sim.NewSessionRequest\x1a%.macro_traffic_sim.NewSessionResponse\"\x00\x12U\n" +
	"\vInfoSession\x12\x1c.macro_traffic_sim.SessionId\x1a&.macro_traffic_sim.InfoSessionResponse\"\x00\x12Y\n" +
	"\rDeleteSession\x12\x1c.macro_traffic_sim.SessionId\x1a(.macro_traffic_sim.DeleteSessionResponse\"\x00\x12]\n" +
	"\vPushNetwork\x12\x1f.macro_traffic_sim.NetworkChunk\x1a'.macro_traffic_sim.NetworkChunkResponse\"\x00(\x010\x01\x12U\n" +
	"\tPushZones\x12\x1c.macro_traffic_sim.ZoneChunk\x1a$.macro_traffic_sim.ZoneChunkResponse\"\x00(\x010\x01\x12`\n" +
	"\fPushOdMatrix\x12 .macro_traffic_sim.OdMatrixChunk\x1a(.macro_traffic_sim.OdMatrixChunkResponse\"\x00(\x010\x01\x12a\n" +
	"\x0eSetModelConfig\x12%.macro_traffic_sim.ModelConfigRequest\x1a&.macro_traffic_sim.ModelConfigResponse\"\x00\x12`\n" +
	"\vRunPipeline\x12%.macro_traffic_sim.RunPipelineRequest\x1a&.macro_traffic_sim.RunPipelineProgress\"\x000\x01\x12`\n" +
	"\x0eGetLinkVolumes\x12%.macro_traffic_sim.LinkVolumesRequest\x1a#.macro_traffic_sim.LinkVolumesChunk\"\x000\x01\x12W\n" +
	"\rGetSkimMatrix\x12\x1e.macro_traffic_sim.SkimRequest\x1a\".macro_traffic_sim.SkimMatrixChunk\"\x000\x01\x12W\n" +
	"\vGetOdResult\x12\".macro_traffic_sim.OdResultRequest\x1a .macro_traffic_sim.OdResultChunk\"\x000\x01\x12j\n" +
	"\x11GetAssignmentInfo\x12(.macro_traffic_sim.AssignmentInfoRequest\x1a).macro_traffic_sim.AssignmentInfoResponse\"\x00B@Z>github.com/LdDl/macro_traffic_sim_grpc/clients/go;macrotrafficb\x06proto3"

var file_service_proto_goTypes = []any{
	(*NewSessionRequest)(nil),      // 0: macro_traffic_sim.NewSessionRequest
	(*SessionId)(nil),              // 1: macro_traffic_sim.SessionId
	(*NetworkChunk)(nil),           // 2: macro_traffic_sim.NetworkChunk
	(*ZoneChunk)(nil),              // 3: macro_traffic_sim.ZoneChunk
	(*OdMatrixChunk)(nil),          // 4: macro_traffic_sim.OdMatrixChunk
	(*ModelConfigRequest)(nil),     // 5: macro_traffic_sim.ModelConfigRequest
	(*RunPipelineRequest)(nil),     // 6: macro_traffic_sim.RunPipelineRequest
	(*LinkVolumesRequest)(nil),     // 7: macro_traffic_sim.LinkVolumesRequest
	(*SkimRequest)(nil),            // 8: macro_traffic_sim.SkimRequest
	(*OdResultRequest)(nil),        // 9: macro_traffic_sim.OdResultRequest
	(*AssignmentInfoRequest)(nil),  // 10: macro_traffic_sim.AssignmentInfoRequest
	(*NewSessionResponse)(nil),     // 11: macro_traffic_sim.NewSessionResponse
	(*InfoSessionResponse)(nil),    // 12: macro_traffic_sim.InfoSessionResponse
	(*DeleteSessionResponse)(nil),  // 13: macro_traffic_sim.DeleteSessionResponse
	(*NetworkChunkResponse)(nil),   // 14: macro_traffic_sim.NetworkChunkResponse
	(*ZoneChunkResponse)(nil),      // 15: macro_traffic_sim.ZoneChunkResponse
	(*OdMatrixChunkResponse)(nil),  // 16: macro_traffic_sim.OdMatrixChunkResponse
	(*ModelConfigResponse)(nil),    // 17: macro_traffic_sim.ModelConfigResponse
	(*RunPipelineProgress)(nil),    // 18: macro_traffic_sim.RunPipelineProgress
	(*LinkVolumesChunk)(nil),       // 19: macro_traffic_sim.LinkVolumesChunk
	(*SkimMatrixChunk)(nil),        // 20: macro_traffic_sim.SkimMatrixChunk
	(*OdResultChunk)(nil),          // 21: macro_traffic_sim.OdResultChunk
	(*AssignmentInfoResponse)(nil), // 22: macro_traffic_sim.AssignmentInfoResponse
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: macro_traffic_sim.MacroService.NewSession:input_type -> macro_traffic_sim.NewSessionRequest
	1,  // 1: macro_traffic_sim.MacroService.InfoSession:input_type -> macro_traffic_sim.SessionId
	1,  // 2: macro_traffic_sim.MacroService.DeleteSession:input_type -> macro_traffic_sim.SessionId
	2,  // 3: macro_traffic_sim.MacroService.PushNetwork:input_type -> macro_traffic_sim.NetworkChunk
	3,  // 4: macro_traffic_sim.MacroService.PushZones:input_type -> macro_traffic_sim.ZoneChunk
	4,  // 5: macro_traffic_sim.MacroService.PushOdMatrix:input_type -> macro_traffic_sim.OdMatrixChunk
	5,  // 6: macro_traffic_sim.MacroService.SetModelConfig:input_type -> macro_traffic_sim.ModelConfigRequest
	6,  // 7: macro_traffic_sim.MacroService.RunPipeline:input_type -> macro_traffic_sim.RunPipelineRequest
	7,  // 8: macro_traffic_sim.MacroService.GetLinkVolumes:input_type -> macro_traffic_sim.LinkVolumesRequest
	8,  // 9: macro_traffic_sim.MacroService.GetSkimMatrix:input_type -> macro_traffic_sim.SkimRequest
	9,  // 10: macro_traffic_sim.MacroService.GetOdResult:input_type -> macro_traffic_sim.OdResultRequest
	10, // 11: macro_traffic_sim.MacroService.GetAssignmentInfo:input_type -> macro_traffic_sim.AssignmentInfoRequest
	11, // 12: macro_traffic_sim.MacroService.NewSession:output_type -> macro_traffic_sim.NewSessionResponse
	12, // 13: macro_traffic_sim.MacroService.InfoSession:output_type -> macro_traffic_sim.InfoSessionResponse
	13, // 14: macro_traffic_sim.MacroService.DeleteSession:output_type -> macro_traffic_sim.DeleteSessionResponse
	14, // 15: macro_traffic_sim.MacroService.PushNetwork:output_type -> macro_traffic_sim.NetworkChunkResponse
	15, // 16: macro_traffic_sim.MacroService.PushZones:output_type -> macro_traffic_sim.ZoneChunkResponse
	16, // 17: macro_traffic_sim.MacroService.PushOdMatrix:output_type -> macro_traffic_sim.OdMatrixChunkResponse
	17, // 18: macro_traffic_sim.MacroService.SetModelConfig:output_type -> macro_traffic_sim.ModelConfigResponse
	18, // 19: macro_traffic_sim.MacroService.RunPipeline:output_type -> macro_traffic_sim.RunPipelineProgress
	19, // 20: macro_traffic_sim.MacroService.GetLinkVolumes:output_type -> macro_traffic_sim.LinkVolumesChunk
	20, // 21: macro_traffic_sim.MacroService.GetSkimMatrix:output_type -> macro_traffic_sim.SkimMatrixChunk
	21, // 22: macro_traffic_sim.MacroService.GetOdResult:output_type -> macro_traffic_sim.OdResultChunk
	22, // 23: macro_traffic_sim.MacroService.GetAssignmentInfo:output_type -> macro_traffic_sim.AssignmentInfoResponse
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_uuid_proto_init()
	file_session_proto_init()
	file_network_proto_init()
	file_config_proto_init()
	file_run_proto_init()
	file_results_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
