// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: session.proto

package macrotraffic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Session creation request (empty; session starts with default state)
type NewSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewSessionRequest) Reset() {
	*x = NewSessionRequest{}
	mi := &file_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSessionRequest) ProtoMessage() {}

func (x *NewSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSessionRequest.ProtoReflect.Descriptor instead.
func (*NewSessionRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0}
}

// Server response for new session creation
type NewSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response code (0 = OK)
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable message
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Session identifier (UUIDv4)
	SessionId     *UUIDv4 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewSessionResponse) Reset() {
	*x = NewSessionResponse{}
	mi := &file_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSessionResponse) ProtoMessage() {}

func (x *NewSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSessionResponse.ProtoReflect.Descriptor instead.
func (*NewSessionResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{1}
}

func (x *NewSessionResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NewSessionResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *NewSessionResponse) GetSessionId() *UUIDv4 {
	if x != nil {
		return x.SessionId
	}
	return nil
}

// Session identifier wrapper
type SessionId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *UUIDv4                `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionId) Reset() {
	*x = SessionId{}
	mi := &file_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionId) ProtoMessage() {}

func (x *SessionId) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionId.ProtoReflect.Descriptor instead.
func (*SessionId) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{2}
}

func (x *SessionId) GetValue() *UUIDv4 {
	if x != nil {
		return x.Value
	}
	return nil
}

// Session state description
type InfoSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response code (0 = OK)
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable message
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Session identifier
	SessionId *UUIDv4 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Current session state
	State string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"` // "empty", "network_loaded", "configured", "running", "completed"
	// Data presence flags
	HasNetwork  bool `protobuf:"varint,5,opt,name=has_network,json=hasNetwork,proto3" json:"has_network,omitempty"`
	HasZones    bool `protobuf:"varint,6,opt,name=has_zones,json=hasZones,proto3" json:"has_zones,omitempty"`
	HasOdMatrix bool `protobuf:"varint,7,opt,name=has_od_matrix,json=hasOdMatrix,proto3" json:"has_od_matrix,omitempty"`
	HasConfig   bool `protobuf:"varint,8,opt,name=has_config,json=hasConfig,proto3" json:"has_config,omitempty"`
	HasResults  bool `protobuf:"varint,9,opt,name=has_results,json=hasResults,proto3" json:"has_results,omitempty"`
	// Network stats (populated after PushNetwork)
	NumNodes      uint32 `protobuf:"varint,10,opt,name=num_nodes,json=numNodes,proto3" json:"num_nodes,omitempty"`
	NumLinks      uint32 `protobuf:"varint,11,opt,name=num_links,json=numLinks,proto3" json:"num_links,omitempty"`
	NumZones      uint32 `protobuf:"varint,12,opt,name=num_zones,json=numZones,proto3" json:"num_zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoSessionResponse) Reset() {
	*x = InfoSessionResponse{}
	mi := &file_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoSessionResponse) ProtoMessage() {}

func (x *InfoSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoSessionResponse.ProtoReflect.Descriptor instead.
func (*InfoSessionResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{3}
}

func (x *InfoSessionResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InfoSessionResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *InfoSessionResponse) GetSessionId() *UUIDv4 {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *InfoSessionResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *InfoSessionResponse) GetHasNetwork() bool {
	if x != nil {
		return x.HasNetwork
	}
	return false
}

func (x *InfoSessionResponse) GetHasZones() bool {
	if x != nil {
		return x.HasZones
	}
	return false
}

func (x *InfoSessionResponse) GetHasOdMatrix() bool {
	if x != nil {
		return x.HasOdMatrix
	}
	return false
}

func (x *InfoSessionResponse) GetHasConfig() bool {
	if x != nil {
		return x.HasConfig
	}
	return false
}

func (x *InfoSessionResponse) GetHasResults() bool {
	if x != nil {
		return x.HasResults
	}
	return false
}

func (x *InfoSessionResponse) GetNumNodes() uint32 {
	if x != nil {
		return x.NumNodes
	}
	return 0
}

func (x *InfoSessionResponse) GetNumLinks() uint32 {
	if x != nil {
		return x.NumLinks
	}
	return 0
}

func (x *InfoSessionResponse) GetNumZones() uint32 {
	if x != nil {
		return x.NumZones
	}
	return 0
}

// Server response for session deletion
type DeleteSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response code (0 = OK)
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable message
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSessionResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteSessionResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_session_proto protoreflect.FileDescriptor

const file_session_proto_rawDesc = "" +
	"\n" +
	"\rsession.proto\x12\x11macro_traffic_sim\x1a\n" +
	"uuid.proto\"\x13\n" +
	"\x11NewSessionRequest\"v\n" +
	"\x12NewSessionResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x128\n" +
	"\n" +
	"session_id\x18\x03 \x01(\v2\x19.macro_traffic_sim.UUIDv4R\tsessionId\"<\n" +
	"\tSessionId\x12/\n" +
	"\x05value\x18\x01 \x01(\v2\x19.macro_traffic_sim.UUIDv4R\x05value\"\x86\x03\n" +
	"\x13InfoSessionResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x128\n" +
	"\n" +
	"session_id\x18\x03 \x01(\v2\x19.macro_traffic_sim.UUIDv4R\tsessionId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1f\n" +
	"\vhas_network\x18\x05 \x01(\bR\n" +
	"hasNetwork\x12\x1b\n" +
	"\thas_zones\x18\x06 \x01(\bR\bhasZones\x12\"\n" +
	"\rhas_od_matrix\x18\a \x01(\bR\vhasOdMatrix\x12\x1d\n" +
	"\n" +
	"has_config\x18\b \x01(\bR\thasConfig\x12\x1f\n" +
	"\vhas_results\x18\t \x01(\bR\n" +
	"hasResults\x12\x1b\n" +
	"\tnum_nodes\x18\n" +
	" \x01(\rR\bnumNodes\x12\x1b\n" +
	"\tnum_links\x18\v \x01(\rR\bnumLinks\x12\x1b\n" +
	"\tnum_zones\x18\f \x01(\rR\bnumZones\"?\n" +
	"\x15DeleteSessionResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04textB@Z>github.com/LdDl/macro_traffic_sim_grpc/clients/go;macrotrafficb\x06proto3"

var (
	file_session_proto_rawDescOnce sync.Once
	file_session_proto_rawDescData []byte
)

func file_session_proto_rawDescGZIP() []byte {
	file_session_proto_rawDescOnce.Do(func() {
		file_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)))
	})
	return file_session_proto_rawDescData
}

var file_session_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_session_proto_goTypes = []any{
	(*NewSessionRequest)(nil),     // 0: macro_traffic_sim.NewSessionRequest
	(*NewSessionResponse)(nil),    // 1: macro_traffic_sim.NewSessionResponse
	(*SessionId)(nil),             // 2: macro_traffic_sim.SessionId
	(*InfoSessionResponse)(nil),   // 3: macro_traffic_sim.InfoSessionResponse
	(*DeleteSessionResponse)(nil), // 4: macro_traffic_sim.DeleteSessionResponse
	(*UUIDv4)(nil),                // 5: macro_traffic_sim.UUIDv4
}
var file_session_proto_depIdxs = []int32{
	5, // 0: macro_traffic_sim.NewSessionResponse.session_id:type_name -> macro_traffic_sim.UUIDv4
	5, // 1: macro_traffic_sim.SessionId.value:type_name -> macro_traffic_sim.UUIDv4
	5, // 2: macro_traffic_sim.InfoSessionResponse.session_id:type_name -> macro_traffic_sim.UUIDv4
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_session_proto_init() }
func file_session_proto_init() {
	if File_session_proto != nil {
		return
	}
	file_uuid_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_session_proto_goTypes,
		DependencyIndexes: file_session_proto_depIdxs,
		MessageInfos:      file_session_proto_msgTypes,
	}.Build()
	File_session_proto = out.File
	file_session_proto_goTypes = nil
	file_session_proto_depIdxs = nil
}
